### ISSUE TITLE
[Bug] Default ChatQnA service gives incorrect output for seed question when testing with curl

### ISSUE THREAD

**Issue by devpramod** [opea-project/GenAIExamples#1005]
### Priority

P2-High

### OS type

Ubuntu

### Hardware type

Xeon-SPR

### Installation method

- [X] Pull docker images from hub.docker.com
- [ ] Build docker images from source

### Deploy method

- [X] Docker compose
- [ ] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

https://hub.docker.com/layers/opea/chatqna/latest/images/sha256-b6fe31dd33dc819054b6ae850ef45e1572d62e80305164759bed852638a0c691?context=explore

### Description

When using the default compose.yaml file for Xeon on IBM cloud ( `bx3d-16x80` instance on IBM Cloud. It has 16 vCPU, 80GB RAM and 100GB boot volume), the output for the question `What is the revenue of Nike in 2023?`  is not as expected, or close to accepted.
Also tried the question `what is the capital city of France?`

Attaching the output logs:

Question: What is the revenue of Nike in 2023?
[default_output.txt](https://github.com/user-attachments/files/17464380/default_output.txt)

Question: What is the capital of France?
[default_output_paris.txt](https://github.com/user-attachments/files/17464392/default_output_paris.txt)

if you limit the tokens, the output is just truncated and the user doesn't get the answer:

Question: What is the capital of France? (max tokens=10)
[truncated.txt](https://github.com/user-attachments/files/17464415/truncated.txt)

### Reproduce steps

git clone https://github.com/opea-project/GenAIExamples.git
cd GenAIExamples/ChatQnA

cd docker_compose/intel/cpu/xeon/
source set_env.sh

docker compose up -d

```
curl http://${host_ip}:8888/v1/chatqna     -H "Content-Type: application/json"     -d '{
        "messages": "What is the revenue of Nike in 2023?"
    }'
```

**Comment by lvliang-intel** [comment]
@devpramod,
could you please try again with latest docker image?
