### ISSUE TITLE
[Bug] CodeTrans generates inconsistent and random outputs when processing dummy code inputs

### ISSUE THREAD

**Issue by lianhao** [opea-project/GenAIExamples#1012]
### Priority

Undecided

### OS type

Ubuntu

### Hardware type

Gaudi2

### Installation method

- [ ] Pull docker images from hub.docker.com
- [X] Build docker images from source

### Deploy method

- [X] Docker compose
- [ ] Docker
- [ ] Kubernetes
- [X] Helm

### Running nodes

Single Node

### What's the version?

commit a3f9811f7ef3d561357674218c64b4cb9d42803a

### Description

![codetrans_bug](https://github.com/user-attachments/assets/1d8a029c-002e-43bd-ae0d-f1e4bcb1c9f4)

The code snippets generated seems random and inconsistent for dummy code

### Reproduce steps

launch the CodeTrans, and input as the above 

### Raw log

```shell
no errors found in the docker compose logs
```

**Comment by lvliang-intel** [comment]
PR https://github.com/opea-project/GenAIExamples/pull/1013 fix this issue, please retest.  Replace codegen default Model to Qwen/Qwen2.5-Coder-7B-Instruct.

**Comment by lianhao** [comment]
verified that the new model works
