### ISSUE TITLE
[Bug] Text in Getting Started needs to be converted to link

### ISSUE THREAD

**Issue by arun-gupta** [opea-project/GenAIExamples#1024]
### Priority

Undecided

### OS type

Ubuntu

### Hardware type

Xeon-GNR

### Installation method

- [ ] Pull docker images from hub.docker.com
- [ ] Build docker images from source

### Deploy method

- [ ] Docker compose
- [ ] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

None

### Description

OPEA Getting Started guide should include links

There are several links mentioned in the `Get Involved` section at https://opea-project.github.io/latest/getting-started/README.html#get-involved. All of them are just simple text and instead should be specified as links.

Also, the second bullet referring to `CodeGen` example needs to be converted to a link.

### Reproduce steps

https://opea-project.github.io/latest/getting-started/README.html

**Comment by yinghu5** [comment]
thank you a lot, fix them by https://github.com/opea-project/docs/pull/229
