### ISSUE TITLE
[Bug] DocSum cannot support requests

### ISSUE THREAD

**Issue by lianghouxu** [opea-project/GenAIExamples#1028]
### Priority

Undecided

### OS type

Ubuntu

### Hardware type

Xeon-GNR

### Installation method

- [ ] Pull docker images from hub.docker.com
- [X] Build docker images from source

### Deploy method

- [ ] Docker compose
- [ ] Docker
- [ ] Kubernetes
- [X] Helm

### Running nodes

Single Node

### What's the version?

latest code of 2024-10-25

### Description

# curl docsum mega svc:
curl http://10.104.36.218:8888/v1/docsum -H "Content-Type: application/json" -d '{"messages": "Text Embeddings Inference (TEI) is a toolkit for deploying and serving open source text embeddings and sequence classification models. TEI enables high-performance extraction for the most popular models, including FlagEmbedding, Ember, GTE and E5."}'

return:
{"detail":[{"type":"missing","loc":["body","files"],"msg":"Field required","input":null}]}

### Reproduce steps

1. start docsum service with helm
2. curl request to docsum megs svc

### Raw log

```shell
{"detail":[{"type":"missing","loc":["body","files"],"msg":"Field required","input":null}]}

INFO:     127.0.0.1:50224 - "POST /v1/docsum HTTP/1.1" 422 Unprocessable Entity
INFO:     10.240.203.70:16751 - "POST /v1/docsum HTTP/1.1" 422 Unprocessable Entity
```

**Comment by xiguiw** [comment]
@lianghouxu 
Please follow the [instruction to submit the request]
(https://github.com/opea-project/GenAIExamples/blob/main/DocSum/docker_compose/intel/cpu/xeon/README.md)

```
curl http://${host_ip}:8888/v1/docsum \
    -H "Content-Type: multipart/form-data" \
    -F "messages=Text Embeddings Inference (TEI) is a toolkit for deploying and serving open source text embeddings and sequence classification models. TEI enables high-performance extraction for the most popular models, including FlagEmbedding, Ember, GTE and E5." \
    -F "max_tokens=32" \
    -F "language=en" \
    -F "stream=false"
```

**Comment by lianghouxu** [comment]
it works great. thanks.

**Comment by eero-t** [comment]
> @lianghouxu Please follow the [instruction to submit the request](https://github.com/opea-project/GenAIExamples/blob/main/DocSum/docker_compose/intel/cpu/xeon/README.md)
> 
> ```
> curl http://${host_ip}:8888/v1/docsum \
>     -H "Content-Type: multipart/form-data" \
>     -F "messages=Text Embeddings Inference (TEI) is a toolkit for deploying and serving open source text embeddings and sequence classification models. TEI enables high-performance extraction for the most popular models, including FlagEmbedding, Ember, GTE and E5." \
>     -F "max_tokens=32" \
>     -F "language=en" \
>     -F "stream=false"
> ```

Tried using "latest" images available from DockerHub => DocSum gives "Internal Server error".    In logs I see error message indicating it expects JSON.  When giving same thing in JSON, it still gives "Internal Server error" unless one uses "stream=true", which provides fairly unreadable out (seems about same as what LLM uservice provides).

=> @lianghouxu Which version is supposed to work?

**Comment by eero-t** [comment]
Ah, it changed last week.  HEAD documentation could mention this API change and refer to v1.0 docs, e.g:
> Note: v1.0 queries are in JSON format, see: https://github.com/opea-project/GenAIExamples/tree/v1.0rc/DocSum
