### ISSUE TITLE
[Bug] DocSum Svelte UI failed to send request

### ISSUE THREAD

**Issue by Ruoyu-y** [opea-project/GenAIExamples#1065]
### Priority

P2-High

### OS type

Ubuntu

### Hardware type

Xeon-SPR

### Installation method

- [ ] Pull docker images from hub.docker.com
- [X] Build docker images from source

### Deploy method

- [X] Docker compose
- [ ] Docker
- [X] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

opea/docsum-ui:latest with commit id 89f4c5fb41ba69ecee4c986b744a016889d39d13

### Description

DocSum UI failed to send request the backend services. I could found such error in the web console:
```
Uncaught (in promise) TypeError: Failed to execute 'append' on 'FormData': parameter 2 is not of type 'Blob'.
    at Dl (2.Blofns3j.js:8:9152)
    at s (2.Blofns3j.js:10:1591)
    at Gl.i (2.Blofns3j.js:10:1888)
    at scheduler.BP_N31YS.js:1:6251
    at Array.forEach (<anonymous>)
    at scheduler.BP_N31YS.js:1:6237
    at g (2.Blofns3j.js:8:3816)
    at HTMLButtonElement.b (2.Blofns3j.js:8:3912)
```

### Reproduce steps

Build the UI image from source code and start the docsum example.

**Comment by Ruoyu-y** [comment]
@WenjiaoYue Can you help with the issue? Looks like it is related to your last code changes in the `DocSum/ui/svelte/src/lib/shared/Network.ts` :
```
if (params === "doc_id" && file) {
    formData.append("files", file, fileName);
    formData.append("messages", query);
```

**Comment by WenjiaoYue** [comment]
OK, I'm looking into this issue and will let you know once it's resolved.
