### ISSUE TITLE
 Connection reset by peer

### ISSUE THREAD

**Issue by apahleva** [opea-project/GenAIExamples#113]
@lvliang-intel,
I am following the steps in the README, and after I successfully build the Docker container and set up my Hugging Face token, I encounter an issue that I don't know how to resolve. Can you guide me?

curl -v --noproxy '*' 127.0.0.1:8080/generate -X POST -d '{"inputs":"What is Deep Learning?","parameters":{"max_new_tokens":32}}' -H 'Content-Type: application/json'
Note: Unnecessary use of -X or --request, POST is already inferred.

Trying 127.0.0.1:8080...
TCP_NODELAY set
Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
POST /generate HTTP/1.1
Host: 127.0.0.1:8080
User-Agent: curl/7.68.0
Accept: /
Content-Type: application/json
Content-Length: 70

upload completely sent off: 70 out of 70 bytes
Recv failure: Connection reset by peer
Closing connection 0
curl: (56) Recv failure: Connection reset by peer

**Comment by lvliang-intel** [comment]
@apahleva,

Thanks for raising this issue. Did you use 'docker logs <container id>' to check if the model startup successfully? It needs some time to warmup the LLM.

**Comment by xiguiw** [comment]
close as no more action required.
