### ISSUE TITLE
[Bug]Max output tokens from an LLM should be configurable. 

### ISSUE THREAD

**Issue by mkbhanda** [opea-project/GenAIExamples#1131]
### Priority

P2-High

### OS type

Ubuntu

### Hardware type

Xeon-SPR

### Installation method

- [X] Pull docker images from hub.docker.com
- [ ] Build docker images from source

### Deploy method

- [ ] Docker compose
- [ ] Docker
- [X] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

Development branch, post V1.0.

### Description

The ChatQnA example appears to be using the max_tokens parameter to control the number of output llm tokens, but it is not getting passed along if the re-ranker component is removed from the pipeline. 
Perhaps we have a bug in Mega or in the token used. The OpenAI openAPI uses  max_completion_tokens and we perhaps have migrated to this incompletely.  We may need to also check GenAIComps.

This was noticed by @leslieluyu.

### Reproduce steps

Run ChatQnA without re-ranker and try to control the maximum output tokens by passing in some value.

**Comment by lvliang-intel** [comment]
@yao531441,
Please help to check this issue. The maximum output tokens setting should not be related with reranking.

**Comment by yao531441** [comment]
@mkbhanda @leslieluyu  Can you provide more detailed steps to reproduce? Our test using Docker to start chatqna without reranking are normal.
![image](https://github.com/user-attachments/assets/8f70bc5b-12f9-44c6-95b1-d02a8e2f98a5)

**Comment by joshuayao** [comment]
Hi @mkbhanda, this issue was fixed in v1.1. Could we close this issue?

**Comment by mkbhanda** [comment]
Thank you!!!
