### ISSUE TITLE
[Bug] Cleanup -- remove image https://hub.docker.com/r/opea/llm-vllm-hpu/tags

### ISSUE THREAD

**Issue by mkbhanda** [opea-project/GenAIExamples#1140]
### Priority

P4-Low

### OS type

Ubuntu

### Hardware type

Xeon-ICX

### Installation method

- [ ] Pull docker images from hub.docker.com
- [ ] Build docker images from source

### Deploy method

- [X] Docker compose
- [X] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

 https://hub.docker.com/layers/opea/llm-vllm-hpu/latest/images/sha256-9cb12c8433758c4fc8c08ef1c3739a0ed3c6ec5f1f881874d104cd7d19188d20?context=explore

### Description

Do we want to keep this image around or delete? At least remove all variants after the v1.0 tag.
Given the following change: https://github.com/opea-project/GenAIExamples/pull/1061/files

### Reproduce steps

none

**Comment by joshuayao** [comment]
Hi @mkbhanda, it would be helpful to keep the deprecated image on Docker Hub for a while, as it was last updated a month ago. I agree with your suggestion to remove it if there are no new pulls after two releases. In v1.2, we will mention in the release notes that the image will be removed, and then proceed with its removal in v1.3. Looking forward to hearing your thoughts.

**Comment by mkbhanda** [comment]
Sounds good! 😊
________________________________

**Comment by joshuayao** [comment]
We will continue tracking the pulls of the image and determine which version to remove based on the conclusions from the discussion above.
