### ISSUE TITLE
[Bug] Redirect docs.opea.dev https://opea-project.github.io/latest/index.html

### ISSUE THREAD

**Issue by arun-gupta** [opea-project/GenAIExamples#1188]
### Priority

Undecided

### OS type

Ubuntu

### Hardware type

Xeon-GNR

### Installation method

- [ ] Pull docker images from hub.docker.com
- [ ] Build docker images from source

### Deploy method

- [ ] Docker compose
- [ ] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

`latest`

### Description

Can we redirect docs.opea.dev to https://opea-project.github.io/latest/index.html?

Today, docs.opea.dev goes to

<img width="1334" alt="image" src="https://github.com/user-attachments/assets/b5f0fdc2-87d1-45dd-a5cd-ade3b697bb53">

Additionally, capture all incomplete links to opea.dev and guide them back to opea.dev.

### Reproduce steps

As above

**Comment by chickenrae** [comment]
@NeoZhangJianyu How is this going? Any help needed?

**Comment by chickenrae** [comment]
I'm going to see if I can get the web team at Linux Foundation to make this happen!
