### ISSUE TITLE
[Bug] DocSum failed on Gaudi

### ISSUE THREAD

**Issue by chensuyue** [opea-project/GenAIExamples#1229]
### Priority

P1-Stopper

### OS type

Ubuntu

### Hardware type

Gaudi2

### Installation method

- [ ] Pull docker images from hub.docker.com
- [x] Build docker images from source

### Deploy method

- [X] Docker compose
- [ ] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

340796bbae61d38a6aae4d244eef8d583101c04e

### Description

https://github.com/opea-project/GenAIExamples/actions/runs/12142010040/job/33896729882 

### Reproduce steps

https://github.com/opea-project/GenAIExamples/actions/runs/12142010040/job/33896729882

### Raw log

![image](https://github.com/user-attachments/assets/2d0805eb-57c9-4d15-abe0-d9a0422a8b8e)

**Comment by chensuyue** [comment]
@MSCetin37

**Comment by MSCetin37** [comment]
This issue is addressed in [1231](https://github.com/opea-project/GenAIExamples/pull/1231)

**Comment by MSCetin37** [comment]
@chensuyue, @ashahba , @feng-intel,
This issue is solved, but merge https://github.com/opea-project/GenAIExamples/pull/992 is causing a DocSum Megaservice failure, which is not within the scope of this issue.
