### ISSUE TITLE
[Bug]Build UI Docker Image issue with docker command

### ISSUE THREAD

**Issue by js333031** [opea-project/GenAIExamples#1258]
### Priority

Undecided

### OS type

Ubuntu

### Hardware type

Xeon-EMR

### Installation method

- [ ] Pull docker images from hub.docker.com
- [X] Build docker images from source

### Deploy method

- [ ] Docker compose
- [X] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

Latest from github

### Description

Following the steps from [here](https://github.com/opea-project/GenAIExamples/blob/main/ProductivitySuite/docker_compose/intel/cpu/xeon/README.md), steps 1-8 work but step 9 fails :
```
cd GenAIExamples/ProductivitySuite/ui
docker build --no-cache -t ProductivitySuite/docker_compose/intel/cpu/xeon/compose.yaml docker/Dockerfile.react .
```

Error:
```
(base) jays@llmtest:~/data/Dec17OPEA/GenAIExamples/ProductivitySuite/ui$ docker build --no-cache -t /home/jays/data/Dec17OPEA/GenAIExamples/ProductivitySuite/docker_compose/intel/cpu/xeon/compose.yaml docker/Dockerfile.react .
ERROR: "docker buildx build" requires exactly 1 argument.
See 'docker buildx build --help'.

Usage:  docker buildx build [OPTIONS] PATH | URL | -

Start a build
(base) jays@llmtest:~/data/Dec17OPEA/GenAIExamples/ProductivitySuite/ui$
```

### Reproduce steps

See description

**Comment by js333031** [comment]
Should Step 9 be:
```
cd GenAIExamples/ProductivitySuite/ui
docker build --no-cache -t opea/productivity-suite-react-ui-server:latest -f docker/Dockerfile.react .
```

**Comment by xiguiw** [comment]
@js333031 Thanks for catching this error.

We will fix it.

Thanks a lot!
