### ISSUE TITLE
Retrievar microservice CURL command in ChatQnA example Readme for Xeon does not work.

### ISSUE THREAD

**Issue by mandalrajiv** [opea-project/GenAIExamples#155]
In the Readme.md at https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA/microservice/xeon, there is a Retriever Microservice curl command, the command given is:
curl http://${host_ip}:7000/v1/retrieval\
  -X POST \
  -d '{"text":"What is the revenue of Nike in 2023?","embedding":${your_embedding}}' \
  -H 'Content-Type: application/json'

The above command does not work, gives an error `{"detail":[{"type":"json_invalid","loc":["body",59],"msg":"JSON decode error","input":{},"ctx":{"error":"Expecting value"}}]}'

The correct format of the command should be as below.
curl http://${host_ip}:7000/v1/retrieval \
  -X POST \
  -d '{"text":"What is the revenue of Nike in 2023?","embedding":"'"${your_embedding}"'"}' \
  -H 'Content-Type: application/json'

**Comment by kding1** [comment]
You are expected to replace the ${your_embedding} with the actual value printed from the above code snippet in the readme. Basically it's 768 dimension 1-d array.
