### ISSUE TITLE
ChantQnA example on Xeon in AWS needs security groups to be opened

### ISSUE THREAD

**Issue by mandalrajiv** [opea-project/GenAIExamples#157]
For running the Xeon example for ChatQnA in AWS, certain security groups for the EC2 instance need to be opened. The Readme.md instruction should be updated for the same. Below are the details for the security groups to be opened.

For running in the AWS EC2 instance open the necessary ports in the instance's security group. Below is an example. Please open relevant IPV4 addresses for these ports based on your requirements.

redis-vector-db
===============
Port 6379 - Open to 0.0.0.0/0
Port 8001 - Open to 0.0.0.0/0

tei_embedding_service
=====================
Port 6006 - Open to 0.0.0.0/0

embedding
=========
Port 6000 - Open to 0.0.0.0/0

retriever
=========
Port 7000 - Open to 0.0.0.0/0

tei_xeon_service
================
Port 8808 - Open to 0.0.0.0/0

reranking
=========
Port 8000 - Open to 0.0.0.0/0

tgi_service
===========
Port 9009 - Open to 0.0.0.0/0

llm
===
Port 9000 - Open to 0.0.0.0/0

chaqna-xeon-backend-server
==========================
Port 8888 - Open to 0.0.0.0/0

chaqna-xeon-ui-server
=====================
Port 5173 - Open to 0.0.0.0/0

**Comment by kding1** [comment]
Thanks! Yes we will add those instructions in the readme. @lvliang-intel

**Comment by hshen14** [comment]
Done in https://github.com/opea-project/GenAIExamples/pull/156
