### ISSUE TITLE
Incorrect path for the building UI docker image in ChatQnA example for Gaudi

### ISSUE THREAD

**Issue by rajiv-sudo** [opea-project/GenAIExamples#188]
In the instructions at https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA/docker-composer/gaudi, the command to build the UI docker image is:

cd GenAIExamples/ChatQnA/ui/
docker build --no-cache -t opea/gen-ai-comps:chatqna-ui-server --build-arg https_proxy=$https_proxy --build-arg http_proxy=$http_proxy -f ./docker/Dockerfile .

The correct command should be:
cd ui/
docker build --no-cache -t opea/gen-ai-comps:chatqna-ui-server --build-arg https_proxy=$https_proxy --build-arg http_proxy=$http_proxy -f ./docker/Dockerfile .

**Comment by xiguiw** [comment]
@rajiv-sudo 
Thanks for try ChatQnA.
It assumes the default work directory is root of GenAIExample.
For each item,  just take it as a new start. Do not keep the state previous directory.

**Comment by xiguiw** [comment]
close it as no more action required.
