### ISSUE TITLE
Incorrect number of docker images in the Readme for ChatQnA example for Gaudi

### ISSUE THREAD

**Issue by rajiv-sudo** [opea-project/GenAIExamples#189]
In the instructions at https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA/docker-composer/gaudi, it says

Then run the command docker images, you will have the following 7 Docker Images:

It should say instead:
Then run the command docker images, you will have the following 8 Docker Images:

opea/gen-ai-comps:embedding-tei-server
opea/gen-ai-comps:retriever-redis-server
opea/gen-ai-comps:reranking-tei-server
opea/gen-ai-comps:llm-tgi-gaudi-server
opea/tei-gaudi
opea/gen-ai-comps:dataprep-redis-server
opea/gen-ai-comps:chatqna-megaservice-server
opea/gen-ai-comps:chatqna-ui-server

**Comment by devpramod** [comment]
@rajiv-sudo This issue has been fixed in the latest update
