### ISSUE TITLE
Incorrect folder reference in the ChatQnA Readme for docker gaudi

### ISSUE THREAD

**Issue by mandalrajiv** [opea-project/GenAIExamples#231]
In the Readme for the ChatQnA Docker Gaudi example, one of the folder structure is not correct based on the current state of the folders as of 30-May-2024 1:38 pm PST.

In the 9. Build UI Docker Image step, it says:
cd GenAIExamples/ChatQnA/ui/
docker build --no-cache -t opea/chatqna-ui:latest --build-arg https_proxy=$https_proxy --build-arg http_proxy=$http_proxy -f ./docker/Dockerfile .

The directory is wrong. It should be:
cd GenAIExamples/ChatQnA/docker/ui/
docker build --no-cache -t opea/chatqna-ui:latest --build-arg https_proxy=$https_proxy --build-arg http_proxy=$http_proxy -f ./docker/Dockerfile .

**Comment by srinarayan-srikanthan** [comment]
Yes, this is a ReadMe issue. Thank you for bringing this up, will update it.

**Comment by mandalrajiv** [comment]
@srinarayan-srikanthan - thank you
