### ISSUE TITLE
Incorrect folder reference in the ChatQnA Readme for docker compose command for Gaudi

### ISSUE THREAD

**Issue by mandalrajiv** [opea-project/GenAIExamples#232]
In the Readme for the ChatQnA Docker Gaudi example, one of the folder structure is not correct based on the current state of the folders as of 30-May-2024 1:38 pm PST.

Start all the services Docker Containers step, it says:
cd GenAIExamples/ChatQnA/docker-composer/gaudi/
docker compose -f docker_compose.yaml up -d

The directory is wrong. It should be:
cd GenAIExamples/ChatQnA/docker/gaudi/
docker compose -f docker_compose.yaml up -d

**Comment by srinarayan-srikanthan** [comment]
Yes, this is a ReadMe issue. Thank you for bringing this up, will update it.

**Comment by mandalrajiv** [comment]
@srinarayan-srikanthan  - thank you.
