### ISSUE TITLE
Correct location for CoC

### ISSUE THREAD

**Issue by arun-gupta** [opea-project/GenAIExamples#272]
Move the CoC from https://github.com/opea-project/GenAIExamples/blob/main/CODE_OF_CONDUCT.md to https://github.com/opea-project/Governance as this is widely applicable to the entire project.

**Comment by preethivenkatesh** [comment]
@arun-gupta Does the change seem reasonable?

**Comment by chensuyue** [comment]
As the PR shows we have unify those docs into https://github.com/opea-project/docs/pull/21, I will close this issue. Feel free to re-open if you have new comments.
