### ISSUE TITLE
ChatQnA: Issue with UI

### ISSUE THREAD

**Issue by wsfowler** [opea-project/GenAIExamples#281]
Testing the Xeon version of ChatQnA using the `ChatQnA/tests/test_chatqna_on_xeon.sh` and all of the services pass except for the UI:

```shell
Mega service start minimal duration is 0s, maximal duration(including docker image build) is 0s
[ tei-embedding ] HTTP status is 200. Checking content...
[ tei-embedding ] Content is as expected.
[ embedding ] HTTP status is 200. Checking content...
[ embedding ] Content is as expected.
[ retrieval ] HTTP status is 200. Checking content...
[ retrieval ] Content is as expected.
[ tei-rerank ] HTTP status is 200. Checking content...
[ tei-rerank ] Content is as expected.
[ rerank ] HTTP status is 200. Checking content...
[ rerank ] Content is as expected.
[ tgi-llm ] HTTP status is 200. Checking content...
[ tgi-llm ] Content is as expected.
[ llm ] HTTP status is 200. Checking content...
[ llm ] Content is as expected.
[ mega-chatqna ] HTTP status is 200. Checking content...
[ mega-chatqna ] Content is as expected.
```

```shell
Running 3 tests using 3 workers
  1) [webkit] › chatQnA.spec.ts:67:2 › Upload file › should upload a file ──────────────────────────

    Error: expect(received).toContain(expected) // indexOf

    Expected substring: "Uploaded successfully"
    Received string:    "Uploaded failed ×"

      27 |      const notification = await page.waitForSelector(".notification");
      28 |      const notificationText = await notification.textContent();
    > 29 |      expect(notificationText).toContain(expectedText);
         |                               ^
      30 | }
      31 |
      32 | // Helper function: Enter message to chat

        at checkNotificationText (/root/GenAIExamples/ChatQnA/docker/ui/svelte/tests/chatQnA.spec.ts:29:27)
        at uploadFile (/root/GenAIExamples/ChatQnA/docker/ui/svelte/tests/chatQnA.spec.ts:45:2)
        at /root/GenAIExamples/ChatQnA/docker/ui/svelte/tests/chatQnA.spec.ts:71:3

  1 failed
    [webkit] › chatQnA.spec.ts:67:2 › Upload file › should upload a file ───────────────────────────
  2 passed (24.4s)
```

The UI is showing up, but it isn't responding.

![image](https://github.com/opea-project/GenAIExamples/assets/19275861/690b1567-931c-433b-b744-aa2381d2808c)

I've looked through the container logs and no errors are standing out.

**Comment by xiguiw** [comment]
Hi @wsfowler 

Welcome to GenAIExamples!

I would like to know in such environment did you test ChatQnA and UI.
1. How did you set the host_ip of ChatQnA environment?
    Especially the BACKEND_SERVICE_ENDPOINT.  UI server depends on the environment.

2. Where do you run the ChatQnA/tests/test_chatqna_on_xeon.sh, from Xeon Console?
3. In which machine did you start the browser? Could this machine (start the machine) access the meage service, i.e   BACKEND_SERVICE_ENDPOINT?

Thanks!

**Comment by wsfowler** [comment]
> Hi @wsfowler
> 
> Welcome to GenAIExamples!
> 
> I would like to know in such environment did you test ChatQnA and UI.
  - In AWS using the m7i.16xlarge instance type.
> 
> 1. How did you set the host_ip of ChatQnA environment?
>    Especially the BACKEND_SERVICE_ENDPOINT.  UI server depends on the environment.
      - The test script sets all of the environment variables.
> 2. Where do you run the ChatQnA/tests/test_chatqna_on_xeon.sh, from Xeon Console?
      - Yes, I was logged into the Xeon host and ran the script from the console on the Xeon host.
> 3. In which machine did you start the browser? Could this machine (start the machine) access the meage service, i.e   BACKEND_SERVICE_ENDPOINT?
      - I will double check this. 
> 
> Thanks!

**Comment by wsfowler** [comment]
@xiguiw Here is what I get when I access the BACKEND_SERVICE_ENDPOINT:

![image](https://github.com/opea-project/GenAIExamples/assets/19275861/9298209c-7e0d-4346-b01a-930bff94981e)

**Comment by wsfowler** [comment]
The script was picking up the local IP to use for the endpoints, but it should've been using the public IP. Closing this issue, but there should be some note or maybe architecture diagram that discusses this.
