### ISSUE TITLE
End-to-end RAG example using OPEA on AWS

### ISSUE THREAD

**Issue by kevinintel** [opea-project/GenAIExamples#297]
Deploy RAG on AWS

**Comment by kevinintel** [comment]
will add jian-feng.ding@intel.com

**Comment by wsfowler** [comment]
Been working on this. Need my latest PR #310 merged.

This is the Ansible playbook for it: https://github.com/intel/optimized-cloud-recipes/tree/opea-xeon/recipes/ai-opea-chatqna-xeon

**Comment by wsfowler** [comment]
Just got the PR for this merged in: https://github.com/intel/terraform-intel-aws-vm/tree/main/examples/gen-ai-xeon-opea-chatqna

**Comment by kevinintel** [comment]
Thanks [wsfowler](https://github.com/wsfowler).
Did you validate it on AWS?

**Comment by wsfowler** [comment]
> Thanks [wsfowler](https://github.com/wsfowler). Did you validate it on AWS?

Fixed a small typo, but I validated it this morning on AWS.

**Comment by kevinintel** [comment]
Thanks, please add the readme and the configs in OPEA.
 You can create folder like AWS_Deploy in ChatQnA
