### ISSUE TITLE
Validation examples out of date

### ISSUE THREAD

**Issue by eero-t** [opea-project/GenAIExamples#323]
Examples here: https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA/docker/xeon#validate-microservices

Seem to be out of date as several of the services (e.g. LLM) complain:
`{"detail":"Not Found"}`

**Comment by eero-t** [comment]
My earlier test was with v0.6 services, but same happens also with latest Git HEAD ones.

**Comment by YuningQiu** [comment]
Hello, I tested the latest ChatQnA example on AWS EC2 m7i instance, and it can work.
![image](https://github.com/opea-project/GenAIExamples/assets/113460727/487b429f-ed70-4a47-8787-f53e6410e440)

Could you please try one more time or let me know besides LLM, which microservice you also encounter issues? Thanks a lot!

**Comment by eero-t** [comment]
It works for me now too.  Maybe I used incorrect service IP. => Feel free to close.

However, it would help if validation examples and also line for getting the correct SVC URL.

In addition to that, I would suggest improving the validation examples by:
* re-arranging the curl lines for readability:
  * args are always given the same way in same position
  * the unique part (`-d` arg) on a line of its own, as last item
  * dropping `-X POST` as `-d` implies that
* Using "service" vs "microservice" terminology consistently IMHO "service" is fine)

----

Like this:
```
ns=default # OPEA services namespace
```

1. TEI Embedding service
```
$ svc_url=$(kubectl -n $ns get svc | sed 's#[:/].*##' | awk '/^tei-embedding/ {printf("%s:%s", $3, $5)}')
$ curl $svc_url/embed -H 'Content-Type: application/json' \
  -d '{"inputs":"What is Deep Learning?"}'
```

2. Embedding service
```
$ svc_url=$(kubectl -n $ns get svc | sed 's#[:/].*##' | awk '/^embedding-svc/ {printf("%s:%s", $3, $5)}')
$ curl $svc_url/v1/embeddings -H 'Content-Type: application/json' \
  -d '{"text":"hello"}'
```

3.  Retriever service

To validate the retriever microservice, you need to generate a mock embedding vector of length 768 for the `cURL` command:
```
$ embedding=$(python3 -c "import random; print([random.uniform(-1, 1) for _ in range(768)])")
$ svc_url=$(kubectl -n $ns get svc | sed 's#[:/].*##' | awk '/^retriever-svc/ {printf("%s:%s", $3, $5)}')
$ curl $svc_url/v1/retrieval -H 'Content-Type: application/json' \
  -d '{"text":"What is the revenue of Nike in 2023?","embedding":"'"${embedding}"'"}'
```

4. TEI Reranking service
```
$ svc_url=$(kubectl -n $ns get svc | sed 's#[:/].*##' | awk '/^tei-reranking/ {printf("%s:%s", $3, $5)}')
$ curl $svc_url/rerank -H 'Content-Type: application/json' \
  -d '{"query":"What is Deep Learning?", "texts": ["Deep Learning is not...", "Deep learning is..."]}'
```

5. Reranking service
```
$ svc_url=$(kubectl -n $ns get svc | sed 's#[:/].*##' | awk '/^reranking-svc/ {printf("%s:%s", $3, $5)}')
$ curl $svc_url/v1/reranking -H 'Content-Type: application/json' \
  -d '{"initial_query":"What is Deep Learning?", "retrieved_docs": [{"text":"Deep Learning is not..."}, {"text":"Deep learning is..."}]}'
```

6. TGI Service
```
$ svc_url=$(kubectl -n $ns get svc | sed 's#[:/].*##' | awk '/^tgi-svc/ {printf("%s:%s", $3, $5)}')
$ curl $svc_url/generate -H 'Content-Type: application/json' \
  -d '{"inputs":"What is Deep Learning?","parameters":{"max_new_tokens":17, "do_sample": true}}'
```

7. LLM service
```
$ svc_url=$(kubectl -n $ns get svc | sed 's#[:/].*##' | awk '/^llm-svc/ {printf("%s:%s", $3, $5)}')
$ curl $svc_url/v1/chat/completions -H 'Content-Type: application/json' \
  -d '{"query":"What is Deep Learning?","max_new_tokens":17,"top_k":10,"top_p":0.95,"typical_p":0.95,"temperature":0.01,"repetition_penalty":1.03,"streaming":true}'
```

8. Megaservice
```
$ svc_url=$(kubectl -n $ns get svc | sed 's#[:/].*##' | awk '/^chaqna-xeon-/ {printf("%s:%s", $3, $5)}')
$ curl $svc_url/v1/chatqna -H "Content-Type: application/json" \
  -d '{"messages": "What is the revenue of Nike in 2023?"}'
```

etc.

**Comment by YuningQiu** [comment]
Thanks a lot for your kind suggestions! We will take them into consideration!
