### ISSUE TITLE
Documentation: DocSum main README motivation

### ISSUE THREAD

**Issue by mkbhanda** [opea-project/GenAIExamples#338]
The motivation paragraph-2 is more general and perhaps should move up as paragraph-1. Original paragraph-1 gets too specific into legal documents prematurely.

 gets prematurelyhttps://github.com/opea-project/GenAIExamples/tree/main/DocSum#readme

Further the HW options figure implies by not mentioning Xeon in the TGI area that one needs Gaudi when that is not the case.

The document also does not at the end branch off into docker versus Kubernetes instructions. I will try to address this last as part of Kubernetes support soon.

**Comment by yinghu5** [comment]
Hi  [mkbhanda](https://github.com/mkbhanda),  

Fixed the first part by #621, please help review and add other parts if needed. 

thank you!
