### ISSUE TITLE
Multimodality

### ISSUE THREAD

**Issue by kevinintel** [opea-project/GenAIExamples#358]

**Comment by tileintel** [comment]
We have submitted the RFC for MM-RAG based Visual QnA application [here](https://github.com/opea-project/docs/pull/49). I would much appreciate if anyone can review this. Thanks

**Comment by tileintel** [comment]
For Multimodal RAG on Videos application, we have created the PR `https://github.com/opea-project/GenAIComps/pull/547` for multimodal embedding microservice. 
@chensuyue @lvliang-intel @kevinintel: **Important note**: Could you please review this PR before the PR [https://github.com/opea-project/GenAIComps/pull/538](https://github.com/opea-project/GenAIComps/pull/538).

Thanks

**Comment by kevinintel** [comment]
Only comps PR: https://github.com/opea-project/GenAIComps/pull/547

**Comment by kevinintel** [comment]
Hi tiep, 
I can't link to your PR  because the catgory is GenAIExamples.
Will you create examples after comps PR merged?

**Comment by tileintel** [comment]
> Hi tiep, I can't link to your PR because the catgory is GenAIExamples. Will you create examples after comps PR merged?

I see. Yes, we will have 2 to 3 GenAIExamples PR after all comps PR merged. 
Thanks for letting me know this.

**Comment by tileintel** [comment]
I had to close the PR [https://github.com/opea-project/GenAIComps/pull/547](https://github.com/opea-project/GenAIComps/pull/547), and replace that with the new PR [https://github.com/opea-project/GenAIComps/pull/555](https://github.com/opea-project/GenAIComps/pull/555). This is to resolve required DCO test.

**Comment by tileintel** [comment]
@kevinintel We have just created another PR in GenAIComps for [multimodal dataprep microservice](https://github.com/opea-project/GenAIComps/pull/575). 
Would you please ask someone to review it?
Also, the previous PR [https://github.com/opea-project/GenAIComps/pull/555](https://github.com/opea-project/GenAIComps/pull/555) hasn't been reviewed yet. 

Thanks

**Comment by tileintel** [comment]
@kevinintel We have created 2 PRs for 2 usecases of MultimodalRAGQnA application. Can you please update this issue to link with them? Both of the PR are under WIP.
#751 
#744 
Thanks a lot

**Comment by tileintel** [comment]
@kevinintel All PRs for GenAIComps have been merged. The two PRs #751 and #744 have been merged. I think this issue is done. Can you please mark done and close this?
