### ISSUE TITLE
Publish Docker images for Xeon sample

### ISSUE THREAD

**Issue by arun-gupta** [opea-project/GenAIExamples#361]
The steps to deploy the sample on Xeon are documented at https://github.com/opea-project/GenAIExamples/blob/main/ChatQnA/docker/xeon/README.md. There should be no need for every developer to build the Docker image.

Can we publish the Docker images in `opea` namespace?

**Comment by yinghu5** [comment]
thank you for raising the problem, will consider it in the OPEA roadmap.  thank you!

**Comment by eero-t** [comment]
@arun-gupta I think image provision depends on fixing https://github.com/opea-project/GenAIComps/issues/264.

(Whereas e.g. applying significant image size reductions described in  https://github.com/opea-project/GenAIComps/issues/265 and https://github.com/opea-project/GenAIExamples/issues/225 would just be nice to have.)

**Comment by ashahba** [comment]
I'm working on this task since mid last week and all PRs are done.
We are hoping sometimes this week, we can publish all images.

**Comment by ashahba** [comment]
@arun-gupta 
All containers are published here for v0.7: https://hub.docker.com/u/opea

Would you be check and close this ticket as done.

Thanks.

**Comment by eero-t** [comment]
> @arun-gupta All containers are published here for v0.7: https://hub.docker.com/u/opea

Currently all images seem to have no descriptions.  Would be good to have there some indication of the purpose of the image, components included to it and their licensing (BOM).

**Comment by arun-gupta** [comment]
@eero-t that's a fair feedback. can you file another issue for that?

**Comment by eero-t** [comment]
> @eero-t that's a fair feedback. can you file another issue for that?

@arun-gupta filed #400.
