### ISSUE TITLE
Make tgi-gaudi compatible with driver versions

### ISSUE THREAD

**Issue by chensuyue** [opea-project/GenAIExamples#366]

**Comment by lkk12014402** [comment]
### description:

1.15.x docker can't run on 1.16.x driver
![image](https://github.com/opea-project/GenAIExamples/assets/33276950/5b18df77-bdc4-4381-bc24-5b47110fa7c6)

![image](https://github.com/opea-project/GenAIExamples/assets/33276950/90dba5aa-d145-4e27-ae70-9b6d0e100834)


### solution

#### reset container driver not work

https://docs.habana.ai/en/latest/Orchestration/OpenShift_User_Guide/Load_habanalabs_Driver.html

1. can't install the `Intel Gaudi Software Stack` in the container successfully
![image](https://github.com/opea-project/GenAIExamples/assets/33276950/699aa8d2-eee4-4f16-9d8b-b660b5fb9e85)

2. copy the `Intel Gaudi Software Stack` to host, not friendly
![image](https://github.com/opea-project/GenAIExamples/assets/33276950/d0055ca7-d90f-438b-be78-b46c0c0956f7)

#### give explanations at document

**Comment by lkk12014402** [comment]
with two envs `-e INIT_HCCL_ON_ACQUIRE=0 -e ENABLE_EXPERIMENTAL_FLAGS=true`, 1.15.x docker can run 1.16.x driver

docker run -p 8080:80 --runtime=habana -e INIT_HCCL_ON_ACQUIRE=0 -e ENABLE_EXPERIMENTAL_FLAGS=true -e http_proxy=$http_proxy -e https_proxy=$https_proxy -e PT_HPU_ENABLE_LAZY_COLLECTIVES=true -e HABANA_VISIBLE_DEVICES=all -e OMPI_MCA_btl_vader_single_copy_mechanism=none --cap-add=sys_nice --ipc=host ghcr.io/huggingface/tgi-gaudi:2.0.0 --model-id Intel/neural-chat-7b-v3-1 --max-input-tokens 1024 --max-total-tokens 2048

**Comment by lkk12014402** [comment]
model=BAAI/bge-large-en-v1.5
volume=$PWD/data
docker run -p 8090:80 -v $volume:/data --runtime=habana -e HABANA_VISIBLE_DEVICES=all -e https_proxy="http://child-jf.intel.com:912" -e http_proxy="http://child-jf.intel.com:912" -e OMPI_MCA_btl_vader_single_copy_mechanism=none -e MAX_WARMUP_SEQUENCE_LENGTH=512 --cap-add=sys_nice --ipc=host ghcr.io/huggingface/tei-gaudi:latest --model-id $model --pooling cls
