### ISSUE TITLE
MegaService is giving empty response in chatQnA 

### ISSUE THREAD

**Issue by skuma31** [opea-project/GenAIExamples#373]
My current setup:
![Screenshot 2024-07-03 234730](https://github.com/opea-project/GenAIExamples/assets/60603468/163c985f-b642-4773-8482-ed8b900865fa)

Mega service giving nothing for curl requests:
![Screenshot 2024-07-03 235752](https://github.com/opea-project/GenAIExamples/assets/60603468/72b5005c-a075-4307-9dcd-df9f5cf49426)

Please let me know if you need anything else to fix this.

**Comment by xiguiw** [comment]
Mega service depends on LLM microservice. 
If you LLM microservice does not work, you cannot expect Mega works.

**Comment by skuma31** [comment]
Thank you @yinghu5 . The issue was due to Hugginface API token and now it is working. I will close this ticket.
