### ISSUE TITLE
The browser UI  http://{host_ip}:5173 not responding to the queries

### ISSUE THREAD

**Issue by skuma31** [opea-project/GenAIExamples#374]
My current running setup:

![Screenshot 2024-07-03 234730](https://github.com/opea-project/GenAIExamples/assets/60603468/6b927d5d-1704-4d29-9f8a-9401c80af44b)

UI is not responding to the submitted queries:

![Screenshot 2024-07-04 000054](https://github.com/opea-project/GenAIExamples/assets/60603468/5add78b5-eb87-427f-82a8-1ac2d1577d78)

Please let me know if you need any additional information.

**Comment by yinghu5** [comment]
Hi Skuma31,  should be similar issue  #https://github.com/opea-project/GenAIExamples/issues/281, please check if the server connect is ok

**Comment by xiguiw** [comment]
Duplicated issues.
Mega service does not work. It's expected UI gets no response, no data.

**Comment by skuma31** [comment]
It is working now. Thank you.
