### ISSUE TITLE
New sample using Graph database 

### ISSUE THREAD

**Issue by arun-gupta** [opea-project/GenAIExamples#386]
I presented an OPEA workshop at a private event this morning. There was a request to use a Graph database backend for business context information. This issue is capturing the request to create a new sample using a Graph database.

**Comment by endomorphosis** [comment]
I am contemplating replacing the backend of graphrag, I did submit a ticket to get the Gaudi text embedding interface working, but I have yet to get feedback from TSC about the design patterns.

**Comment by kevinintel** [comment]
will implemente GraphRAG in v1.0

**Comment by arun-gupta** [comment]
@kevinintel do you have any updates on this?

**Comment by kevinintel** [comment]
We have an initial version: https://github.com/opea-project/GenAIComps/pull/682

**Comment by XuhuiRen** [comment]
https://github.com/opea-project/GenAIExamples/pull/1007
https://github.com/opea-project/GenAIComps/pull/793
these two PR will enable this feature

**Comment by arun-gupta** [comment]
@XuhuiRen where can I find the docs to try this functionality?
