### ISSUE TITLE
ChatQnA mega service failing on GCP

### ISSUE THREAD

**Issue by srinarayan-srikanthan** [opea-project/GenAIExamples#395]
To build the docker images on gcp i had to add an extra flag --network to be able to build the container successfully. I am able to run all the microservices separately and I am not facing any issues.

But running the mega service gives Internal Service Error:
And checking the docker logs shows Jsondecode error
![image](https://github.com/user-attachments/assets/3c158037-7c40-452e-a1d5-86a3fa0809d0)
![image](https://github.com/user-attachments/assets/8b8f4b6f-90cc-4c1b-9da4-b26bd92cf15d)

I see all the containers up and running:

![image](https://github.com/user-attachments/assets/55356c2c-030a-4bf7-aff1-8ea34e212f1a)

Sometimes in the docker logs i see a broken pipe error or aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer

**Comment by lvliang-intel** [comment]
@srinarayan-srikanthan，
Did you validate each microservice like below?
![image](https://github.com/user-attachments/assets/746a1a2d-239d-43e8-80a8-60f03193960f)

**Comment by srinarayan-srikanthan** [comment]
yes i validated each microservice and all of them work fine.

**Comment by eero-t** [comment]
> yes i validated each microservice and all of them work fine.

In same setup as where GCP is running?  And they returned valid content instead of an error?

I'm asking because some of the backend services can take a _long_ time to initialize themselves, _especially on the first run_, if model data is not pre-provisioned.  Backend services do respond early on, but until they're fully up, response is an error message, and caller typically shows that as JSON decode error because error message does not have content it expected.

**Comment by srinarayan-srikanthan** [comment]
Yes, the LLM service takes time to load the first time, but all microservices run well. And i am doing all this in v0.7 tag.

**Comment by eero-t** [comment]
Could you attach the whole backtrace of the error?    Typically it provides the address of the service which returned data it did not recognize.

**Comment by eero-t** [comment]
> Sometimes in the docker logs i see a broken pipe error or aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer

I've just seen something similar after doing doing large number of requests.  My current assumption is that after HuggingFace's TGI or TEI (ChatQnA's LLM backends) input buffer became full, they rejected further connections until inferences for some of the already buffered requests had been completed.

Could this (too large number of parallel requests) be also a problem in your case?

**Comment by srinarayan-srikanthan** [comment]
No I am just sending in one request, so i dont think that is the problem here.

**Comment by srinarayan-srikanthan** [comment]
I tried it on a BM instance on a lab machine and it works fine, only failing on GCP.

**Comment by srinarayan-srikanthan** [comment]
Isolated the issue to the core count for retrieval microservice. Working on it to find the required number of cores and fix it. Issue not present with latest code.

**Comment by srinarayan-srikanthan** [comment]
Resolved in 0.8 release.
