### ISSUE TITLE
CodeGen README.md issue

### ISSUE THREAD

**Issue by Feelas** [opea-project/GenAIExamples#402]
[CodeGen Svelte UI README.md](https://github.com/opea-project/GenAIExamples/blob/ba65415b78d237d180cf9f3654d72b106b7b8a2e/CodeGen/docker/ui/svelte/README.md) points to using BASE_URL, however this specific UI uses BASIC_URL parameter - [e.g. based on Gaudi docker compose](https://github.com/opea-project/GenAIExamples/blob/ba65415b78d237d180cf9f3654d72b106b7b8a2e/CodeGen/docker/gaudi/docker_compose.yaml#L71) & same can be observed by inspecting .env in this app.

**Comment by NeoZhangJianyu** [comment]
@Feelas 
Thank you for your feedback!
We will check and correct it as soon!

**Comment by NeoZhangJianyu** [comment]
We will fix as soon!

**Comment by NeoZhangJianyu** [comment]
It's fixed.
Could you confirm and close this issue if possible?

**Comment by Feelas** [comment]
@NeoZhangJianyu looks good, thank you :)
