### ISSUE TITLE
OPEA project errors from TCS

### ISSUE THREAD

**Issue by preethivenkatesh** [opea-project/GenAIExamples#410]
Repo used for testing
https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA/docker/xeon

OPEA Project Errors

2. Embedding Microservice

curl : Internal Server Error
At line:1 char:1
+ curl -Uri "http://192.168.4.196:6000/v1/embeddings" -Method Post -Bod ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

5.Reranking Microservice

curl : Internal Server Error
At line:1 char:1
+ curl -Uri "http://192.168.4.196:8000/v1/reranking" -Method Post -Body ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

6. TGI Service

curl -Uri "http://192.168.4.196:9009/generate" -Method Post -Body '{"inputs":"What is Deep Learning?","parameters":{"max_new_tokens":17, "do_sample": true}}' -ContentType 'application/json'

7. LLM Microservice

curl -Uri "http://192.168.4.196:9009/generate" -Method Post -Body '{"inputs":"What is Deep Learning?","parameters":{"max_new_tokens":17, "do_sample": true}}' -ContentType 'application/json'

8. Megaservice

curl http://${host_ip}:8888/v1/chatqna -H "Content-Type: application/json" -d '{
     "messages": "What is the revenue of Nike in 2023?"
     }'

**Comment by yinghu5** [comment]
We noticed there are Microsoft.PowerShell.Commands.InvokeWebRequestCommand information, could you please help to check how the customer try the ChatQ&A? 

Do they use one machine with the Windows PowerShell system to access another Linux machine? 

From the message,  Seems the main issue are the network error, 

Like 

2. Embedding Microservice

curl : Internal Server Error
At line:1 char:1
+ curl -Uri http://192.168.4.196:6000/v1/embeddings -Method Post -Bod ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

The microservice expected one external Public IP address,   if they use the local IP address like 192.168.4.196,  then they have to run the command from internal network same as 192.168.4.xxx. 

Xigui have one validation guide:   [GenAIExamples/ChatQnA/docker/gaudi/how_to_validate_service.md at main · opea-project/GenAIExamples (github.com)](https://github.com/opea-project/GenAIExamples/blob/main/ChatQnA/docker/gaudi/how_to_validate_service.md)

The expected IP address is usually like   ${host_ip}= external IP address  

 



Secondly,  can’t us same port for different service :  

6. TGI Service

curl -Uri http://192.168.4.196:9009/generate -Method Post -Body '{"inputs":"What is Deep Learning?","parameters":{"max_new_tokens":17, "do_sample": true}}' -ContentType 'application/json'


7. LLM Microservice

curl -Uri http://192.168.4.196:9009/generate -Method Post -Body '{"inputs":"What is Deep Learning?","parameters":{"max_new_tokens":17, "do_sample": true}}' -ContentType 'application/json'

The expected port should be https://github.com/opea-project/GenAIExamples/blob/main/ChatQnA/docker/gaudi/how_to_validate_service.md

![image](https://github.com/user-attachments/assets/f073be1d-9443-42bf-84a6-120ad217cb9d)

**Comment by yinghu5** [comment]
@Ural, Raghavendra K <raghavendra.k.ural@intel.com>
FYI

**Comment by xiguiw** [comment]
One more thing, 
try 
`curl -vv -X POST http://${host_ip}:6000/v1/embeddings`

1.  replace the host_ip as your host ip addres, 
2. Observe if there is network proxy issue. If you find it try to connect through proxy, put your host_ip into no_proxy.

**Comment by xiguiw** [comment]
Close as no more actions.
