### ISSUE TITLE
Update sample instructions for ChatQnA to use published Docker images

### ISSUE THREAD

**Issue by arun-gupta** [opea-project/GenAIExamples#412]
Docker images for different microservices are published at https://github.com/opea-project/GenAIExamples/issues/361. All the sample instructions should be updated to use those images. "Building the Docker image" instructions are still useful for somebody who wants to tinker with the code and should be move to a different docuemnt.

**Comment by xiguiw** [comment]
@arun-gupta 
After the images are published, we will update the instructions for ChatQnA to use published Docker images.

Is this ticket duplicated to [#361](https://github.com/opea-project/GenAIExamples/issues/361)?

**Comment by xiguiw** [comment]
@arun-gupta 
It seems the Docker images are published. 
After I got the formal messages and verified it, I'll update the instructions. 

Thank you!

**Comment by arun-gupta** [comment]
@xiguiw any updates on this? https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA/docker/xeon#-build-docker-images is redundant

**Comment by xiguiw** [comment]
@arun-gupta 

Please help to review PR#762 for this issue.

There are platforms other than Xeon (Gauid,APIC) to be updated. And other GenAIExamples to be update.

**Comment by xiguiw** [comment]
Document updated.
All docker images could be download by run 
`docker compose up -d`
