### ISSUE TITLE
[ChatQnA Conversational UI] backend URL specified during image build process

### ISSUE THREAD

**Issue by Ruoyu-y** [opea-project/GenAIExamples#493]
According to the readme file, the urls of backend service and data preparation service need to added as build args while building the conversational UI image. However, if the urls get changed during the runtime, it is hard to update back to the UI service. Also, in the case that the UI is deployed simultaneously with the workload or it is pre-deployed before the services, it is hard for user to specify these args as they might be everchanging.

We would like to suggest that the urls get consumed through environment variables during runtime, instead of build args during image creation.

**Comment by Ruoyu-y** [comment]
@zhlsunshine @irisdingbj Add more comments if you have.

**Comment by Ruoyu-y** [comment]
@jaswanth8888 Any comments on this?

**Comment by Feelas** [comment]
I filled a similar issue for CodeGen React UI https://github.com/opea-project/GenAIExamples/issues/505

Seems to be a common theme in all React UI impls.

**Comment by jaswanth8888** [comment]
Hi @Ruoyu-y 
I am working on the same and will raise PR for all the react UI implementations .

**Comment by Ruoyu-y** [comment]
> Hi @Ruoyu-y I am working on the same and will raise PR for all the react UI implementations .

Great. Thanks. Please also help take a look on the following issues related to UI implementation. #517 #518

**Comment by jaswanth8888** [comment]
@Ruoyu-y enabled chat qna to pick env variables during runtime with [PR](https://github.com/opea-project/GenAIExamples/pull/590)
