### ISSUE TITLE
[CodeGen React UI] Is VITE_CODE_GEN_URL a build-time constant?

### ISSUE THREAD

**Issue by Feelas** [opea-project/GenAIExamples#505]
VITE_CODE_GEN_URL is used in building the React UI Dockerfile.
https://github.com/opea-project/GenAIExamples/blob/09a3196324b6b9094852c9a990d2a9346f779cda/CodeGen/docker/ui/docker/Dockerfile.react#L11

Is this environment variable configurable after building the npm app and copying it into nginx container? I tried to pass it via container envs but it doesn't seem to pick it up in the runtime. It would be best to make it very clear in the README that this is only customizable during build time and not in the runtime.

**Comment by xiguiw** [comment]
Fixed. 

Double check, 
`ENV VITE_CODE_GEN_URL=$BACKEND_SERVICE_ENDPOINT  `
is removed from GenAIExamples/CodeGen/docker/ui/docker/Dockerfile.react
