### ISSUE TITLE
[ChatQnA UI] Backend urls must be external urls exposed outside the cluster

### ISSUE THREAD

**Issue by Ruoyu-y** [opea-project/GenAIExamples#518]
UI services need to consume the backend service urls for functioning. Currently, both UI implementations require the endpoint information (aka. these backend urls) to be some external urls that can be accessed outside the cluster.
However, in the case that the UI service is deployed as part of the pipeline, it is hard to specify these external urls as the backend services are not exposed by default and there's no fixed domain names for the backend services. Any chance that the UI could consume an internal k8s service domain name and perform the call?

**Comment by Feelas** [comment]
Second this, especially because UI app calling a different hostname might fail on some browsers (e.g. Firefox) due to CORS issues.

**Comment by lvliang-intel** [comment]
We have added a Nginx microservice into the pipeline. So this issue can be fixed. Can we close this issue?
