### ISSUE TITLE
Error in comps/llms/text-generation/vllm/launch_vllm_service.sh

### ISSUE THREAD

**Issue by devpramod** [opea-project/GenAIExamples#520]
Error Message:

When launching vllm service in comps/llms/text-generation/vllm the following error message appears:
`api_server.py: error: unrecognized arguments: /bin/bash -c cd / && export VLLM_CPU_KVCACHE_SPACE=40 && python3 -m vllm.entrypoints.openai.api_server --model  --host 0.0.0.0 --port 80`

because the entry point for the container is already python3 -m vllm.entrypoints.openai.api_server

A warning also occurs:
WARNING: Published ports are discarded when using host network mode

This is because the vLLM service Docker command uses -p for port mapping and --network=host. This causes Docker to ignore the port mapping.

**Comment by devpramod** [comment]
@kevinintel I created a PR to fix the issue. Based on your recommendation I can make the changes for Gaudi and other comps as well
PR: https://github.com/opea-project/GenAIComps/pull/399

**Comment by kevinintel** [comment]
Thanks [devpramod](https://github.com/devpramod)

**Comment by devpramod** [comment]
Hi @kevinintel One of the issues has been resolved
My PR was closed -  https://github.com/opea-project/GenAIComps/pull/399 which also had resolution for port mapping

in line 43 - https://github.com/opea-project/GenAIComps/blob/main/comps/llms/text-generation/vllm/launch_vllm_service.sh
port mapping is discarded and port 80 is used even in the host

**Comment by devpramod** [comment]
port mapping issue is fixed
