### ISSUE TITLE
Clarify the framework tables on the main page

### ISSUE THREAD

**Issue by arun-gupta** [opea-project/GenAIExamples#521]
The tables on the main page of this repo are confusing. 

Do I read that ChatQnA is tested and validated on LangChain and LlamaIndex? Is each combination tested with different serving models? 

A consistent framework should be picked for testing and all should be tested on those. Ideally, the instructions on how tests are conducted should be made available too. None of the scripts at https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA/tests seem to indicate anything about the framework.

**Comment by kevinintel** [comment]
We refined the Readme, both LangChain and LlamaIndex are verified in GenAIComps.

**Comment by kevinintel** [comment]
Default framework is langchain

**Comment by chickenrae** [comment]
Should this be closed?

**Comment by arun-gupta** [comment]
Yes
