### ISSUE TITLE
Chat QnA UI does not connect to the backend

### ISSUE THREAD

**Issue by ShankarRIntel** [opea-project/GenAIExamples#528]

**Comment by ZailiWang** [comment]
Hi @ShankarRIntel would you elaborate more about how to reproduce this issue? Thanks.

**Comment by ashahba** [comment]
Thanks @ShankarRIntel for submitting this.
This one is for React UI and the error we are getting from the backend is:
```
 File "/home/user/.local/lib/python3.11/site-packages/requests/adapters.py", line 700, in send
llm-vllm-server                      |     raise ConnectionError(e, request=request)
llm-vllm-server                      | requests.exceptions.ConnectionError: HTTPConnectionPool(host='<PUBLIC_IP>', port=4318): Max retries exceeded with url: /v1/traces (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ab67373d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by ashahba** [comment]
![ChatQnA](https://github.com/user-attachments/assets/66f9e65d-39ce-4847-8934-7fd49ca704a3)

**Comment by WenjiaoYue** [comment]
Hi @jaswanth8888, it seems that the React version cannot display the response info normally. Can you help fix this problem? By the way, the React version should also include end-to-end testing similar to Playwright and start the scripts in the CI tests, so every time other developers submit their code, the entire process will be tested thoroughly, ensuring the front-end code works properly or allowing you to make necessary adjustments in a timely manner.

**Comment by chensuyue** [comment]
Hi @jaswanth8888, this is high priority, we will target the fix into v0.8.1 patch release.

**Comment by jaswanth8888** [comment]
Hi @chensuyue , we are working on the fix and will raise a PR for the same

**Comment by jaswanth8888** [comment]
fixed the issue with [PR](https://github.com/opea-project/GenAIExamples/pull/590)
