### ISSUE TITLE
MegaService Dockerfile clone GenAIComps without tag

### ISSUE THREAD

**Issue by gavinlichn** [opea-project/GenAIExamples#530]
GenAIExamples/ChatQnA/docker/Dockerfile:
   git clone https://github.com/opea-project/GenAIComps.git 

that will cause version control issue.

**Comment by xiguiw** [comment]
Hi @gavinlichn,

Do you want to check out a tag of GenAIComp for version control?
This always let the user try the latest code, instead of a fixed version.

For a specific, please check out the specific tag for both GenAIComps and GenAIExamples.
Does this make sense?

Thanks!

**Comment by gavinlichn** [comment]
> Hi @gavinlichn,
> 
> Do you want to check out a tag of GenAIComp for version control? This always let the user try the latest code, instead of a fixed version.
> 
> For a specific, please check out the specific tag for both GenAIComps and GenAIExamples. Does this make sense?
> 
> Thanks!

For a tagged build or milestone, checkout a specific tag is good enough. But I think we need to consider the everyday engineering build also.  Do you have any idea to handle this case also?

**Comment by xiguiw** [comment]
> But I think we need to consider the everyday engineering build also. Do you have any idea to handle this case also?
Do you mean the daily build or weekly build? 
For the weekly build, it is being discussing.
One it is decided, there solution will be proposed.

@chensuyue Do you have any comments for these? Thanks!

**Comment by chensuyue** [comment]
We have proposed a solution for this issue and will execute from v0.9 release. We will freeze all the pip deps version and image tag version instead of using the latest one. Thank you for the comments!

**Comment by gavinlichn** [comment]
> @gavinlichn Does Suyue's proposal solve your problem?

Yes, It's worked since version v0.9
