### ISSUE TITLE
DocSum use case is not working

### ISSUE THREAD

**Issue by TobyBayaua** [opea-project/GenAIExamples#532]
I completed all the steps in deploying DocSum in our EC2 instance but when I placed a text, it did not give me a summary.  I used both svelt based frontend and react based frontend and no summary output.

**Comment by xiguiw** [comment]
docker compose -f ./docker-composer/gaudi/compose.yaml logs

**Comment by TobyBayaua** [comment]
<img width="458" alt="docsum_screen_capture" src="https://github.com/user-attachments/assets/bd302919-c1b5-4a7d-aab0-8bbdeb49ccf8">

**Comment by xiguiw** [comment]
Each container has a compose.yaml.
For DocSum, it is here:
GenAIExamples/DocSum/docker/xeon/compose.yaml

So you point to the relative path to compose.yaml
For example 
```
cd GenAIExamples/DocSum
docker compose -f ./docker/xeon/compose.yaml logs
```

**Comment by TobyBayaua** [comment]
Please see the attached logs in text file. 
[docsum_error.txt](https://github.com/user-attachments/files/16537453/docsum_error.txt)

I can see the logs saying in the last line 'ModuleNotFoundError: No module named 'uvicorn',
