### ISSUE TITLE
AIPC Apps not response

### ISSUE THREAD

**Issue by weiseng-yeap** [opea-project/GenAIExamples#556]
Hi Developer,

We using the GenAIExamples/ChatQnA/docker/aipc/

And testing MegaService:
curl http://${host_ip}:8888/v1/chatqna -H "Content-Type: application/json" -d '{
     "messages": "What is the revenue of Nike in 2023?", "model": "'"${OLLAMA_MODEL}"'"
     }'

And not getting any response.

Please help to advice.

**Comment by xiguiw** [comment]
@weiseng-yeap  

Would you please follow these instructions to check each service status and provide the logs?
[how_to_validate_service.md](https://github.com/opea-project/GenAIExamples/blob/main/ChatQnA/docker/gaudi/how_to_validate_service.md)

**Comment by weiseng-yeap** [comment]
Hi,

We are using the AIPC as already mentioned. This we're refer to:
https://github.com/opea-project/GenAIExamples/blob/main/ChatQnA/docker/aipc/README.md

And also provide you the docker status logs:

user@user-desktop:~$ docker ps -a
CONTAINER ID   IMAGE                                                   COMMAND                  CREATED       STATUS       PORTS                                                                                  NAMES
348d2fd0996b   opea/reranking-tei:latest                               "python reranking_te…"   6 hours ago   Up 6 hours   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp                                              reranking-tei-aipc-server
d8da3e8495ed   ghcr.io/huggingface/text-embeddings-inference:cpu-1.5   "text-embeddings-rou…"   6 hours ago   Up 6 hours   0.0.0.0:8808->80/tcp, :::8808->80/tcp                                                  tei-reranking-server
c08a00851ea9   opea/dataprep-redis:latest                              "python prepare_doc_…"   6 hours ago   Up 6 hours   0.0.0.0:6007->6007/tcp, :::6007->6007/tcp                                              dataprep-redis-server
0e2fe3e2359d   opea/llm-ollama                                         "bash entrypoint.sh"     6 hours ago   Up 6 hours   0.0.0.0:9000->9000/tcp, :::9000->9000/tcp                                              llm-ollama
24a74401cfe7   opea/chatqna-ui:latest                                  "docker-entrypoint.s…"   9 hours ago   Up 6 hours   0.0.0.0:5173->5173/tcp, :::5173->5173/tcp                                              chatqna-aipc-ui-server
71b7efcda215   opea/chatqna:latest                                     "python chatqna.py"      9 hours ago   Up 6 hours   0.0.0.0:8888->8888/tcp, :::8888->8888/tcp                                              chatqna-aipc-backend-server
1993d9efbec1   opea/embedding-tei:latest                               "python embedding_te…"   9 hours ago   Up 6 hours   0.0.0.0:6000->6000/tcp, :::6000->6000/tcp                                              embedding-tei-server
5eaa0beb5ce9   opea/retriever-redis:latest                             "python retriever_re…"   9 hours ago   Up 6 hours   0.0.0.0:7000->7000/tcp, :::7000->7000/tcp                                              retriever-redis-server
babd2759ea9d   redis/redis-stack:7.2.0-v9                              "/entrypoint.sh"         9 hours ago   Up 6 hours   0.0.0.0:6379->6379/tcp, :::6379->6379/tcp, 0.0.0.0:8001->8001/tcp, :::8001->8001/tcp   redis-vector-db
de9cd14aad3e   ghcr.io/huggingface/text-embeddings-inference:cpu-1.5   "text-embeddings-rou…"   9 hours ago   Up 6 hours   0.0.0.0:6006->80/tcp, :::6006->80/tcp                                                  tei-embedding-server

**Comment by xiguiw** [comment]
this is fixed in https://github.com/opea-project/GenAIComps/pull/447
