### ISSUE TITLE
docsum on docker: mega servcie returns weird results

### ISSUE THREAD

**Issue by lianhao** [opea-project/GenAIExamples#562]
Following [docsum readme](https://github.com/opea-project/GenAIExamples/blob/main/DocSum/docker/xeon/README.md), the mega service returns weird things for the following command:

```
curl http://${host_ip}:8888/v1/docsum -H "Content-Type: application/json" -d '{"messages": "Text Embeddings Inference (TEI) is a toolkit for deploying and serving open source text embeddings and sequence classification models. TEI enables high-performance extraction for the most popular models, including FlagEmbedding, Ember, GTE and E5."}'
```

data: {"ops":[{"op":"add","path":"/logs/HuggingFaceEndpoint/streamed_output_str/-","value":" extr"},{"op":"add","path":"/logs/HuggingFaceEndpoint/streamed_output/-","value":" extr"}]}

data: {"ops":[{"op":"add","path":"/logs/HuggingFaceEndpoint/streamed_output_str/-","value":"action"},{"op":"add","path":"/logs/HuggingFaceEndpoint/streamed_output/-","value":"action"}]}

data: {"ops":[{"op":"add","path":"/logs/HuggingFaceEndpoint/streamed_output_str/-","value":" for"},{"op":"add","path":"/logs/HuggingFaceEndpoint/streamed_output/-","value":" for"}]}

data: {"ops":[{"op":"add","path":"/logs/HuggingFaceEndpoint/streamed_output_str/-","value":" widely"},{"op":"add","path":"/logs/HuggingFaceEndpoint/streamed_output/-","value":" widely"}]}

data: {"ops":[{"op":"add","path":"/logs/HuggingFaceEndpoint/streamed_output_str/-","value":" used"},{"op":"add","path":"/logs/HuggingFaceEndpoint/streamed_output/-","value":" used"}]}

data: {"ops":[{"op":"add","path":"/logs/HuggingFaceEndpoint/streamed_output_str/-","value":" models"},{"op":"add","path":"/logs/HuggingFaceEndpoint/streamed_output/-","value":" models"}]}

data: {"ops":[{"op":"add","path":"/logs/HuggingFaceEndpoint/streamed_output_str/-","value":" like"},{"op":"add","path":"/logs/HuggingFaceEndpoint/streamed_output/-","value":" like"}]}

data: {"ops":[{"op":"add","path":"/logs/HuggingFaceEndpoint/streamed_output_str/-","value":" Flag"},{"op":"add","path":"/logs/HuggingFaceEndpoint/streamed_output/-","value":" Flag"}]}

data: {"ops":[{"op":"add","path":"/logs/HuggingFaceEndpoint/streamed_output_str/-","value":"Emb"},{"op":"add","path":"/logs/HuggingFaceEndpoint/streamed_output/-","value":"Emb"}]}

data: {"ops":[{"op":"add","path":"/logs/HuggingFaceEndpoint/streamed_output_str/-","value":"ed"},{"op":"add","path":"/logs/HuggingFaceEndpoint/streamed_output/-","value":"ed"}]}

data: {"ops":[{"op":"add","path":"/logs/HuggingFaceEndpoint/streamed_output_str/-","value":"ding"},{"op":"add","path":"/logs/HuggingFaceEndpoint/streamed_output/-","value":"ding"}]}

**Comment by letonghan** [comment]
hi @lianhao , it's the expected result of `/v1/docsum`.
The meaningful result is in `data.ops[0].value`, and the frontend of DocSum will display it in the way of `data.ops[0].op`.

**Comment by huiyan2021** [comment]
Close as not an issue, feel free to reopen if you still have further questions.
