### ISSUE TITLE
Allow Users to view the retrieved excerpts in ChatQnA 

### ISSUE THREAD

**Issue by yogeshmpandey** [opea-project/GenAIExamples#586]
Currently, in the ChatQnA Demo application, users cannot view the excerpts retrieved from the knowledge base and used by the Language Model (LLM) to generate the answers. It would be beneficial for users to see these excerpts, as it would provide transparency into the reasoning process of the LLM and help users understand the context and sources of the generated answers.

**Comment by lkk12014402** [comment]
hi, retrieval and reranking results are not included in the ChatQnA final response now.

I also think it would be beneficial for users to see retrieval/reranking excerpts. And we will consider this as a new feature.

**Comment by lkk12014402** [comment]
we can request `retriever` microservice to get the retrieval knowledge, refer to https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA/docker_compose/intel/hpu/gaudi#validate-microservices-and-megaservice

![image](https://github.com/user-attachments/assets/11dbafb3-90d4-44dc-a155-184d528b39f9)

**Comment by xiguiw** [comment]
@lkk12014402  @kevinintel @yogeshmpandey 
Is the retriever/reranking micro-service enough for this request?

Some questions:
1. How to convince users the retriever/reranking results are the same as those input to LLM in ChatQnA Example?
2. For the reranking output, retriever output needs to be connected to reranking input. It is missed here.
