### ISSUE TITLE
set_env.sh for ChantQnA on Xeon is missing the REDIS_HOST environment variable

### ISSUE THREAD

**Issue by mandalrajiv** [opea-project/GenAIExamples#591]
set_env.sh for ChantQnA on Xeon is missing the REDIS_HOST environment variable. because of that when I do docker compose up -d, the retriever-redis-server container is showing errors. I solved the problem by adding export REDIS_HOST=${host_ip}

Please add this in the set_env.sh file. Perhaps the same change in needed in other examples as well. Please check.

Error
====
 File "/home/user/.local/lib/python3.11/site-packages/redis/connection.py", line 280, in connect
    raise TimeoutError("Timeout connecting to server")
redis.exceptions.TimeoutError: Timeout connecting to server

https://github.com/opea-project/GenAIExamples/blob/main/ChatQnA/docker/xeon/set_env.sh

**Comment by mandalrajiv** [comment]
Can you please look into this issue?

**Comment by yinghu5** [comment]
@mandalrajiv  thank you very much for the report and fix.   solution is mereged #644
