### ISSUE TITLE
The AIPC on Ollama Service is fail

### ISSUE THREAD

**Issue by weiseng-yeap** [opea-project/GenAIExamples#598]
When we using the AIPC to test the Ollama Service cause connection fail.

Here details:
user@user-desktop:~/GenAIComps/GenAIExamples/ChatQnA/docker/aipc$ curl http://${host_ip}:11434/api/generate -d '{"model": "llama3", "prompt":"What is Deep Learning?"}'
curl: (7) Failed to connect to 10.158.108.60 port 11434 after 0 ms: Connection refused

**Comment by endomorphosis** [comment]
see e.g. https://github.com/opea-project/GenAIComps/issues/367

**Comment by weiseng-yeap** [comment]
I resolved myself with this:

on the ollama.service need to add this:
Environment="OLLAMA_HOST=${host_ip}:11434"
Environment="OLLAMA_ORIGINS=http://${host_ip}:11434"

Then problem resolved.
