### ISSUE TITLE
chatqna-xeon-backend-server crashes due to ports not defined

### ISSUE THREAD

**Issue by liuyingshanx** [opea-project/GenAIExamples#652]
**What I did:**
I followed [https://github.com/opea-project/GenAIExamples/blob/main/ChatQnA/docker/xeon/README_qdrant.md](url) and did all steps to set up chatQnA via docker compose using qdrant as vector db. I Rebuild all images in the latest main branch(Aug. 22, ac324a9ec2ba6a2d2c800e92f0f4e6ccf0948649 is the latest commit id) including opea/chatqna:latest, and apply docker compose yaml file.

**What happens**
Mega container chatqna-xeon-backend-server crashes, the error was:
<img width="870" alt="image" src="https://github.com/user-attachments/assets/97de2f54-f89b-40ac-98ba-eac876a7ee2f">

**How I workaround**
Before applying docker compose yaml file, set those envs:

export EMBEDDING_SERVICE_PORT=6044
export RETRIEVER_SERVICE_PORT=6045
export RERANK_SERVICE_PORT=6046
export LLM_SERVICE_PORT=6047

**Comment by louie-tsai** [comment]
There is a fix for exporting the ports into docker instance in below PR
https://github.com/opea-project/GenAIExamples/pull/569
![image](https://github.com/user-attachments/assets/c1bf4587-9fab-4823-8f8b-f3a490f04402)

Could you try again with the latest codes?

thanks

**Comment by louie-tsai** [comment]
@liuyingshanx 
if no issue any more, we will close the ticket accordingly.

**Comment by louie-tsai** [comment]
feel free to reopen it if issue still exists
