### ISSUE TITLE
ChatQnA UI is missing in k8s deployment

### ISSUE THREAD

**Issue by mixmaier** [opea-project/GenAIExamples#657]
I have successfully deployed chatqna using docker and got UI up and running (exposed under port 5173).
Doing the same under k8s manifest the UI pod is missing. 
https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA/kubernetes/manifests

Can you please include the UI config/svc/deployment in 
https://github.com/opea-project/GenAIExamples/blob/main/ChatQnA/kubernetes/manifests/xeon/chatqna.yaml

Thanks
Michael

**Comment by WenjiaoYue** [comment]
The issue has been resolved. https://github.com/opea-project/GenAIExamples/pull/669
The manifest file now includes Nginx and the UI. Please use the latest image builds for the UI and back_end, and be careful not to upload files with the same name again.
