### ISSUE TITLE
Repeating text generated when using VLLM with Llama

### ISSUE THREAD

**Issue by js333031** [opea-project/GenAIExamples#673]
When using llama models (llama 2, llama 3), a query results in repeating text. For example:
![image](https://github.com/user-attachments/assets/9054f5f6-1bc8-47b3-95f7-cac84c51d6fc)

**Comment by XinyaoWa** [comment]
Hi, I found this was caused by a bug in vllm comps, have fixed in https://github.com/opea-project/GenAIComps/pull/600, please have a check.

**Comment by srinarayan-srikanthan** [comment]
closing as pr merged
