### ISSUE TITLE
VisualQnA UI docker image has backend address hardcoded(not being replaced by envs)

### ISSUE THREAD

**Issue by ezelanza** [opea-project/GenAIExamples#683]
VisualQnA UI image (Gaudi) is not working with the set_env.sh set from https://github.com/opea-project/GenAIExamples/blob/main/VisualQnA/docker/gaudi/README.md

![Screenshot 2024-08-28 at 4 43 24 PM](https://github.com/user-attachments/assets/9213a29f-5632-4362-836e-2690190c3175)

Thanks!

**Comment by wangkl2** [comment]
Thanks for reporting this issue. I will try to reproduce and give feedback later.

**Comment by wangkl2** [comment]
@ezelanza I can reproduce your issue. 

I fix it with this PR https://github.com/opea-project/GenAIExamples/pull/701. After updating the setting in `compose.yaml` for the backend endpoint, it will override the default url setting in [VisualQnA/docker/ui/svelte/.env](https://github.com/opea-project/GenAIExamples/blob/main/VisualQnA/docker/ui/svelte/.env#L1C21-L1C61). Please check it out.

**Comment by ezelanza** [comment]
Thanks, @wangkl2 for that! After replacing the  ```compose.yaml``` as you mentioned, I see the variable correctly changes it to my public_ip (I've covered it for security reasons), but the request from the UI to the backend service seems to be blocked by CORS policy.

![Screenshot 2024-08-30 at 10 55 20 AM](https://github.com/user-attachments/assets/2a7b51fa-2b57-4d44-a5d1-5781804644df)

It works when I test it from any terminal

```
~ % curl http://${host_ip}:8888/v1/visualqna -H "Content-Type: application/json" -d '{
     "messages": [
      {
        "role": "user",
        "content": [
          {
            "type": "text",
            "text": "What'\''s in this image?"
          },
          {
            "type": "image_url",
            "image_url": {
              "url": "https://www.ilankelman.org/stopsigns/australia.jpg"
            }
          }
        ]
      }
    ],
    "max_tokens": 300
    }'
{"id":"chatcmpl-MUqRQ3gWyBjAJqnn4nLuvP","object":"chat.completion","created":1725029828,"model":"visualqna","choices":[{"index":0,"message":{"role":"assistant","content":"The image shows a stop sign at the corner of a street, with a traditional Chinese archway or gateway in the background. There is also a black car driving past the stop sign. The scene suggests a blend of Western and Eastern architectural styles. "},"finish_reason":"stop"}],"usage":{"prompt_tokens":0,"total_tokens":0,"completion_tokens":0}}%  ```
