### ISSUE TITLE
[Discussion] Do we need to open up all the security ports for AWS?

### ISSUE THREAD

**Issue by arun-gupta** [opea-project/GenAIExamples#698]
### Priority

Undecided

### OS type

Ubuntu

### Hardware type

Xeon-SPR

### Installation method

- [X] Pull docker images from hub.docker.com
- [ ] Build docker images from source

### Deploy method

- [X] Docker compose
- [ ] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

0.9

### Description

I'm trying to follow the instructions at https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA/docker/xeon.

Why do we need to open up all these ports in the EC2 Security Group? These services should be talking to each other within the VPC only.

### Reproduce steps

Curious about the need to open up the ports before I start implementing this.

**Comment by xiguiw** [comment]
@arun-gupta The architecture design is to open up gateway port only.

Let me try to get a AWS platform first. Then we can get to know the networks settings on AWS, and we can try and verify the port setting for the GenAIExamples.

**Comment by arun-gupta** [comment]
I've been playing with the setup on AWS. I logged into the EC2 instance and could run a couple of tests locally without opening any ports.

It seems like the ports only needs to be opened up if you do `curl` from the local machine. The instructions already mention that but it is easy to miss.  Can we remove the instructions to open up the port otherwise someone would accidentally do that in production?

Here are my evolving instructions: https://gist.github.com/arun-gupta/7e9f080feff664fbab878b26d13d83d7

**Comment by xiguiw** [comment]
@arun-gupta  

Do you have AWS platform shared with us so I can investigate this issue?
We have no AWS platform.

**Comment by arun-gupta** [comment]
@xiguiw sure, send me an internal Teams message and lets set up offline time to work through this.

**Comment by NeoZhangJianyu** [comment]
I update the guide for AWS user to fix this issue.
Please refer to PR: https://github.com/opea-project/GenAIExamples/pull/849

**Comment by yinghu5** [comment]
Hi Arun
we fixed the problem by PR: https://github.com/opea-project/GenAIExamples/pull/849

close now, please feel free to reopen it if any issues. 

Thank you!
