### ISSUE TITLE
[Bug] ChatQnA on Xeon errors using Docker compose.yaml or compose_vllm.yaml 

### ISSUE THREAD

**Issue by lucasmelogithub** [opea-project/GenAIExamples#704]
### Priority

Undecided

### OS type

Ubuntu

### Hardware type

Xeon-SPR

### Installation method

- [X] Pull docker images from hub.docker.com
- [ ] Build docker images from source

### Deploy method

- [X] Docker compose
- [ ] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

Using main branch

### Description

text-embeddings-inference:cpu-1.5
Version 1.5 errors out.
https://github.com/opea-project/GenAIExamples/blob/main/ChatQnA/docker/xeon/compose.yaml#L73
Changing to 1.4 fixes that issue.

But then we run into errors with chatqna-xeon-backend-server and retriever-redis-server.

We really need well define container versions for all components in dockerhub so we can pin the compose versions.

### Reproduce steps

docker compose -f compose.yaml up

### Raw log

```shell
First error:
tei-reranking-server         | Error: Could not create backend
tei-reranking-server         | 
tei-reranking-server         | Caused by:
tei-reranking-server         |     Could not start backend: Failed to create ONNX Runtime session: Deserialize tensor onnx::MatMul_3214 failed.GetFileLength for /data/models--BAAI--bge-reranker-large/snapshots/55611d7bca2a7133960a6d3b71e083071bbfc312/onnx/model.onnx_data failed:Invalid fd was supplied: -1


Second Error
retriever-redis-server       | INFO:     35.175.182.237:37932 - "POST /v1/retrieval HTTP/1.1" 500 Internal Server Error
chatqna-xeon-backend-server  | embedding/MicroService: 200
chatqna-xeon-backend-server  | retriever/MicroService: 500
chatqna-xeon-backend-server  | INFO:     192.55.54.45:62860 - "POST /v1/chatqna HTTP/1.1" 500 Internal Server Error
chatqna-xeon-backend-server  | ERROR:    Exception in ASGI application

chatqna-xeon-backend-server  | aiohttp.client_exceptions.ContentTypeError: 500, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url='http://35.175.182.237:7000/v1/retrieval'
retriever-redis-server       | ERROR:    Exception in ASGI application
```

**Comment by arun-gupta** [comment]
This may not be directly related but I'm having trouble bringing up TGI Service using Docker Compose on AWS: https://github.com/opea-project/GenAIExamples/issues/706

**Comment by lucasmelogithub** [comment]
Please let me know how I can help do testing. I'm willing to block time if needed @yinghu5 . 

We now have a very large financial service customer wanting a demo of ChatQna on Xeon next week.

**Comment by xiguiw** [comment]
@lucasmelogithub  

What's you model set?

The log indicates invalid ailed:Invalid fd was supplied: -1
```
First error:
tei-reranking-server         | Error: Could not create backend
tei-reranking-server         | 
tei-reranking-server         | Caused by:
tei-reranking-server         |     Could not start backend: Failed to create ONNX Runtime session: Deserialize tensor onnx::MatMul_3214 failed.GetFileLength for /data/models--BAAI--bge-reranker-large/snapshots/55611d7bca2a7133960a6d3b71e083071bbfc312/onnx/model.onnx_data failed:Invalid fd was supplied: -1
```

**Comment by xiguiw** [comment]
1. The platform is with two network settings: a) public network exposed (can be access outside) and b) private network (cannot access outside)
when connect to the network with ssh, it can map ports out:
`ssh user@public_ip -L 5173:locahost:5173 -L 8888:locahost:8888 -L 6007:locahost:6007 xxx`

here we expose `8888, 5173 and 6007` (explain why this ports later)

2. ChatQnA  environment variables setting:
  Set **the public_ip for UI and chatqna services as well as data-prepare** for those we need to access outside.
  Set private ip (host_ip) for other services.
```
export public_ip=<public_ip>
export EMBEDDING_MODEL_ID="BAAI/bge-base-en-v1.5"
export RERANK_MODEL_ID="BAAI/bge-reranker-base"
export LLM_MODEL_ID="Intel/neural-chat-7b-v3-3"
export TEI_EMBEDDING_ENDPOINT="http://${host_ip}:6006"
export TEI_RERANKING_ENDPOINT="http://${host_ip}:8808"
export TGI_LLM_ENDPOINT="http://${host_ip}:9009"
export REDIS_URL="redis://${host_ip}:6379"
export INDEX_NAME="rag-redis"
export REDIS_HOST=${host_ip}
export MEGA_SERVICE_HOST_IP=${host_ip}
export EMBEDDING_SERVICE_HOST_IP=${host_ip}
export RETRIEVER_SERVICE_HOST_IP=${host_ip}
export RERANK_SERVICE_HOST_IP=${host_ip}
export LLM_SERVICE_HOST_IP=${host_ip}
export BACKEND_SERVICE_ENDPOINT="http://${public_ip}:8888/v1/chatqna"
export DATAPREP_SERVICE_ENDPOINT="http://${public_ip}:6007/v1/dataprep"
export DATAPREP_GET_FILE_ENDPOINT="http://${public_ip}:6007/v1/dataprep/get_file"
export DATAPREP_DELETE_FILE_ENDPOINT="http://${public_ip}:6007/v1/dataprep/delete_file"
```

3. ports to be exposed are those we need to access outside:
 `8888, 5173 and 6007`. These ports are public IP.

**Comment by lucasmelogithub** [comment]
@xiguiw and @yinghu5 Thank you for the support. With the additional public_ip variable, this is now working as expected. 
Closing issue.
