### ISSUE TITLE
[Bug]Remove v from Docker image tag names

### ISSUE THREAD

**Issue by arun-gupta** [opea-project/GenAIExamples#722]
### Priority

Undecided

### OS type

Other (Please let us know in description)

### Hardware type

Xeon-other (Please let us know in description)

### Installation method

- [X] Pull docker images from hub.docker.com
- [ ] Build docker images from source

### Deploy method

- [X] Docker compose
- [ ] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

All

### Description

PyTorch tag names are https://hub.docker.com/r/pytorch/pytorch/tags
LangChain tag names are https://hub.docker.com/r/langchain/langchain/tags
Ollama tag names are https://hub.docker.com/r/ollama/ollama/tags

All of them are straight-up version numbers without the prefix `v` that is used in OPEA tags. This letter also feels superfluous. Please change the version numbers to include only numbers.

### Reproduce steps

Tag names are available at https://hub.docker.com/u/opea.

**Comment by chensuyue** [comment]
Ok, we can remove `v` for the image release version from `1.0` release.
