### ISSUE TITLE
[Bug] ChatQnA on Kubernetes has dependency on a directory on worker node

### ISSUE THREAD

**Issue by arun-gupta** [opea-project/GenAIExamples#735]
### Priority

Undecided

### OS type

Ubuntu

### Hardware type

Xeon-GNR

### Installation method

- [ ] Pull docker images from hub.docker.com
- [ ] Build docker images from source

### Deploy method

- [ ] Docker compose
- [ ] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

0.9

### Description

Here is the k8s manifest for ChatQnA: https://raw.githubusercontent.com/opea-project/GenAIExamples/main/ChatQnA/kubernetes/manifests/xeon/chatqna.yaml

It uses a hardcoded path `path: /mnt/opea-models` for model volumes. This directory needs to be explicitly created. Relying upon a specific directory on a node is a non-cloud native way.

### Reproduce steps

Manifest is at: https://raw.githubusercontent.com/opea-project/GenAIExamples/main/ChatQnA/kubernetes/manifests/xeon/chatqna.yaml

**Comment by yongfengdu** [comment]
#745 Fixed at Version 1.0
