### ISSUE TITLE
Remove Intel copyright from sourcecode

### ISSUE THREAD

**Issue by arun-gupta** [opea-project/GenAIExamples#74]
All source code has Intel copyright, we need to remove that and use the recommendation by LF AI & Data.

**Comment by hshen14** [comment]
Hi @arun-gupta, Thanks for reporting the issue. WIP to check with legal about the license change and the potential impact. Btw, could you please point to the recommended license by LF AI & Data? I'd like to share with legal team also.

**Comment by arun-gupta** [comment]
Checking and will get back to you

**Comment by scooter99boston** [comment]
Contributors to the project retain their copyright in the code they contribute. For new contributions, our communities will generally use a community-focused copyright notice such as: "Copyright contributors to the OPEA project", as an example. You can see additional examples and read more on this here: https://www.linuxfoundation.org/blog/blog/copyright-notices-in-open-source-software-projects.

Existing company-specific contribution notices can stay as is, or, for simplicity given that those files may be patched down the road by future contributors, the copyright holder (and only the copyright holder) could transition to the general "Copyright contributors to the OPEA project". Please reach out with any questions. Thank you.

**Comment by yinghu5** [comment]
confirmed and closed. thanks
