### ISSUE TITLE
[Bug] CodeGen - React UI 405 error with Xeon compose.yaml

### ISSUE THREAD

**Issue by lucasmelogithub** [opea-project/GenAIExamples#791]
### Priority

Undecided

### OS type

Ubuntu

### Hardware type

Xeon-GNR

### Installation method

- [X] Pull docker images from hub.docker.com
- [X] Build docker images from source

### Deploy method

- [X] Docker compose
- [ ] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

v0.8/latest

### Description

Get no response from the UI. 
Get 405 HTTP error. Running Curl against other services works. 

### Reproduce steps

git clone https://github.com/opea-project/GenAIExamples
cd GenAIExamples/ChatQnA/docker_compose/intel/cpu/xeon
docker compose -f compose.yaml up -d

### Raw log

```shell
tgi-service                   | 2024-09-11T22:15:41.170563Z  INFO text_generation_router::server: router/src/server.rs:2349: Serving revision b462c3c99b077d341db691ec780a33156f3c1472 of model meta-llama/CodeLlama-7b-hf
tgi-service                   | 2024-09-11T22:15:41.199340Z  INFO text_generation_router::server: router/src/server.rs:1781: Using config Some(Llama)
tgi-service                   | 2024-09-11T22:15:41.199366Z  WARN text_generation_router::server: router/src/server.rs:1928: Invalid hostname, defaulting to 0.0.0.0
tgi-service                   | 2024-09-11T22:15:41.205541Z  INFO text_generation_router::server: router/src/server.rs:2311: Connected
codegen-xeon-react-ui-server  | 192.55.55.46 - - [11/Sep/2024:22:16:08 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0" "-"
codegen-xeon-react-ui-server  | 192.55.55.46 - - [11/Sep/2024:22:16:14 +0000] "POST / HTTP/1.1" 405 559 "http://18.207.121.43/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0" "-"
```

**Comment by xiguiw** [comment]
Fixed by https://github.com/opea-project/GenAIExamples/pull/807

**Comment by lucasmelogithub** [comment]
Verified using the latest version of the main branch. Thank you! Closing.
