### ISSUE TITLE
[Bug]CodeTrans sample fails while looking for opea/nginx image

### ISSUE THREAD

**Issue by arun-gupta** [opea-project/GenAIExamples#830]
### Priority

Undecided

### OS type

Ubuntu

### Hardware type

Xeon-SPR

### Installation method

- [X] Pull docker images from hub.docker.com
- [ ] Build docker images from source

### Deploy method

- [X] Docker compose
- [ ] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

`latest`

### Description

Trying to run CodeTrans sample and the Docker Compose file expects `opea/nginx` image while that does not exist.

### Reproduce steps

Following the instructions at https://github.com/opea-project/GenAIExamples/tree/main/CodeTrans to get the sample running on Xeon. Specific steps are at https://gist.github.com/arun-gupta/5f02b5a57030ba8f975a4c328178ffe8

### Raw log

```shell
[+] Running 2/2
 ✘ codetrans-xeon-nginx-server Error pull access denied for opea/nginx, repository does not exist or may require 'docker login': de...                                    0.8s 
 ✘ codetrans-xeon-ui-server Error    context canceled                                                                                                                     0.8s 
Error response from daemon: pull access denied for opea/nginx, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
ubuntu@ip-172-31-54-128:~$ 
```
```

**Comment by letonghan** [comment]
Hi @arun-gupta , the `opea/nginx` docker image was not officially build in `v0.9`.
It will be ready in `v1.0` release and uploaded to docker hub soon.
We will inform you when this image is ready on docker hub, please wait until then and try again.

**Comment by arun-gupta** [comment]
What is the need to build our own `opea/nginx` image?

**Comment by letonghan** [comment]
This is to customize the configuration file `nginx.conf.template` for opea. It provides more flexibility than using the official nginx docker image directly.

**Comment by letonghan** [comment]
Hi @arun-gupta 
The `opea/nginx:latest` docker image has been officially release in v1.0, and this image will be automatically pulled from docker hub.
