### ISSUE TITLE
Fix code scanning alert - Uncontrolled data used in path expression

### ISSUE THREAD

**Issue by chensuyue** [opea-project/GenAIExamples#833]
Tracking issue for:
- [ ] https://github.com/opea-project/GenAIExamples/security/code-scanning/20

**Comment by tileintel** [comment]
@xiguiw  isn't this one handled already and merged already? I cannot open the link above anymore. Could you please point me to the PR that has this security issue if unresolved yet?

**Comment by xiguiw** [comment]
@tileintel Yes, it is merged. 
I assigned it to you because you resolved the issue.  Just to make sure issues are tracked (and processed).

Thank you!
