### ISSUE TITLE
[Bug]Use pre-built Docker images for Translation instead of trying to build one

### ISSUE THREAD

**Issue by arun-gupta** [opea-project/GenAIExamples#836]
### Priority

Undecided

### OS type

Ubuntu

### Hardware type

Xeon-SPR

### Installation method

- [X] Pull docker images from hub.docker.com
- [ ] Build docker images from source

### Deploy method

- [X] Docker compose
- [ ] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

`latest

### Description

https://github.com/opea-project/GenAIExamples/blob/main/Translation/docker_compose/intel/cpu/xeon/README.md requires the Docker images to be built. Both the images `opea/llm-tgi` and `opea/translation` exist in Docker hub: https://hub.docker.com/u/opea?page=1&search=translation. There should be no need to build this image.

### Reproduce steps

Simplify the instructions to leverage the pre-built Docker images instead of asking developers to build them.

**Comment by letonghan** [comment]
Hi @arun-gupta , thanks for your suggestions. The README of `Translation` example will be updated before `v1.0`.

**Comment by letonghan** [comment]
Close this issue since it has been fixed in PR 847.
