### ISSUE TITLE
[Bug]ChatQnA - K8s - UI port is incorrect in chatqna.yaml

### ISSUE THREAD

**Issue by pallavijaini0525** [opea-project/GenAIExamples#883]
### Priority

P3-Medium

### OS type

Ubuntu

### Hardware type

Gaudi2

### Installation method

- [X] Pull docker images from hub.docker.com
- [ ] Build docker images from source

### Deploy method

- [ ] Docker compose
- [ ] Docker
- [X] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

latest

### Description

https://github.com/opea-project/GenAIExamples/blob/main/ChatQnA/kubernetes/intel/hpu/gaudi/manifest/chatqna.yaml#L286 - Traget Port number for chatqna-ui is given as ui, which is causing the nginx not to open the UI. After changing the port to 5173, it is working as expected. Same issue observed for xeon as well.

### Reproduce steps

Execute /deploy the https://github.com/opea-project/GenAIExamples/blob/main/ChatQnA/kubernetes/intel/hpu/gaudi/manifest/chatqna.yaml and access the NGINX port in browser

**Comment by devpramod** [comment]
@kevinintel 
The issue can be reproduced
The reason is that container port for UI is set to 80 but should be 5173
`containers:
        - name: chatqna-ui
          securityContext:
            {}
          image: "opea/chatqna-ui:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: ui
              containerPort: 80
              protocol: TCP
          resources:
            {}
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      volumes:
        - name: tmp
          emptyDir: {}`

**Comment by letonghan** [comment]
Thanks @preethivenkatesh and @devpramod, we will check it again and fix this issue these days. Any progress will be updated here. Thank you.

**Comment by WenjiaoYue** [comment]
Thanks @preethivenkatesh and @devpramod, we have updated the containerPort. The latest version relies on the backend's no-wrapper image, which will be uploaded in the next couple of days, and then it can be used normally. Thank you for the reminder. If you have any issues, please feel free to contact us anytime..

**Comment by xiguiw** [comment]
@pallavijaini0525 @devpramod 

What's the status now.
Could this be closed?

**Comment by joshuayao** [comment]
Closed for no response in over 30 days. Please reopen it if the issue is still there.
