### ISSUE TITLE
[Bug] ChatQnA unable to retrieve info from file and link

### ISSUE THREAD

**Issue by barryintel** [opea-project/GenAIExamples#901]
### Priority

Undecided

### OS type

Ubuntu

### Hardware type

AI-PC (Please let us know in description)

### Installation method

- [ ] Pull docker images from hub.docker.com
- [X] Build docker images from source

### Deploy method

- [X] Docker compose
- [ ] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Multiple Nodes

### What's the version?

commit 4112fd0b6900452eb99e8428e96884aa8f8bff0b
Author: Sihan Chen <39623753+Spycsh@users.noreply.github.com>
Date:   Thu Sep 12 23:51:47 2024 +0800

### Description

![image](https://github.com/user-attachments/assets/77599b84-a9ba-472c-9015-8571b7542da4)
When upload a link or file it unable to retrieve information base on the link and file. When uploading a file it also load forever.

### Reproduce steps

Follow the same step provided by the ChatQnA AIPC instruction.

Upload a file or link. And ask a question related to the file or link.

### Raw log

```shell
chatqna-aipc-ui-server        | NotFound [Error]: Not found: /v1/dataprep/get_file
chatqna-aipc-ui-server        |     at resolve2 (file:///home/user/svelte/.svelte-kit/output/server/index.js:2896:18)
chatqna-aipc-ui-server        |     at resolve (file:///home/user/svelte/.svelte-kit/output/server/index.js:2723:34)
chatqna-aipc-ui-server        |     at #options.hooks.handle (file:///home/user/svelte/.svelte-kit/output/server/index.js:2962:71)
chatqna-aipc-ui-server        |     at respond (file:///home/user/svelte/.svelte-kit/output/server/index.js:2721:43)
chatqna-aipc-ui-server        |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
chatqna-aipc-ui-server        |   status: 404
chatqna-aipc-ui-server        | }
```

**Comment by ZailiWang** [comment]
Hi, let me try to reproduce and analyze it. Thanks

**Comment by xiguiw** [comment]
@barryintel  Fixed by https://github.com/opea-project/GenAIExamples/pull/933.
Code merged. 
Please verify it.

**Comment by xiguiw** [comment]
@barryintel 
AIPC issue is fixed. 
Please verify it with latest GenAIExample and GenAIComp source code and build image from source code.

**Comment by ksandowi** [comment]
@xiguiw, I have reproduction of this issue on both 1.0 and latest version that is available from 11/06/2024.
The same error is logged by ChatQnA UI while trying to get a response on a request.
NotFound [Error]: Not found: /v1/chatqna
     at resolve2 (file:///home/user/svelte/.svelte-kit/output/server/index.js:2896:18)
     at resolve (file:///home/user/svelte/.svelte-kit/output/server/index.js:2723:34)
     at #options.hooks.handle (file:///home/user/svelte/.svelte-kit/output/server/index.js:2962:71)
     at respond (file:///home/user/svelte/.svelte-kit/output/server/index.js:2721:43)
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
   status: 404
}

At the same time I am able to get responses successfully using Chatqna API:
chatqna_ip_port=$(kubectl get svc chatqna -o=jsonpath='{.spec.clusterIP}'):$(kubectl get svc chatqna -o=jsonpath='{.spec.ports[*].port}')
curl -s http://${chatqna_ip_port}/v1/chatqna -H "Content-Type: application/json" -d '{"model": "Intel/neural-chat-7b-v3-3", "messages": "What is the revenue of Nike in 2023?"}'
