### ISSUE TITLE
[Bug]Docs ask user to set container_id environment variable

### ISSUE THREAD

**Issue by mkbhanda** [opea-project/GenAIExamples#971]
### Priority

P4-Low

### OS type

Ubuntu

### Hardware type

CPU-other (Please let us know in description)

### Installation method

- [X] Pull docker images from hub.docker.com
- [ ] Build docker images from source

### Deploy method

- [ ] Docker compose
- [X] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

https://github.com/opea-project/GenAIExamples/commit/c930bea172d535ca24c51a4419f08547190747e7

### Description

1) For completeness of instructions, particularly when we need to build the docker images, for those specified in GenAIComps, add an instruction to git clone the GenAIComps repo. Also the Docker file refers to the $PYTHON_PATH, need our users to set it.

2) We can improve the documentation in https://github.com/opea-project/GenAIExamples/tree/5dae7137932b0f397e2bfe18bfd2cd94da0dd495/ChatQnA/docker_compose/intel/cpu/xeon
by asking the user to set the container_id environment variable.
docker logs ${CONTAINER_ID} | grep Connected

Better still if we name the LLM service more generically, without mentioning the model serving framework even, such as "llm_service" the command can be even more generic requiring no environment variable setting.

docker logs llm_service | grep Connected

3) While building the docker images
a) for "retriever" and Mega service
 1 warning found (use docker --debug to expand):
 - UndefinedVar: Usage of undefined variable '$PYTHONPATH' (line 24)
b) for Conversational UI build
 1 warning found (use docker --debug to expand):
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 5) 
c)
### Reproduce steps

Follow readme guide.

### Raw log

```shell
devcloud@ubuntu:~$ docker logs ${CONTAINER_ID} | grep Connected
"docker logs" requires exactly 1 argument.
See 'docker logs --help'.

Usage:  docker logs [OPTIONS] CONTAINER

Fetch the logs of a container
```

**Comment by louie-tsai** [comment]
We indeed could use container_name defined in the compose.yaml file and it works.
![image](https://github.com/user-attachments/assets/7a35987e-46c0-433e-8124-403b01f758da)

The only potential issue is having two docker instance with same name, but it should not happen if user uses docker_compose.
if no concern to use container_name defined in compose.yaml, we could change readme accordingly.

also agree on first request, and will work on that too.

**Comment by louie-tsai** [comment]
update ChatQnA accordingly in below PR
https://github.com/opea-project/GenAIExamples/pull/1018

**Comment by louie-tsai** [comment]
Let us know any remining issue in the latest main branch.
if no, we will close it for now.
