### ISSUE TITLE
[Bug] Unable to start all services as Docker Containers ChatQnA

### ISSUE THREAD

**Issue by plischwe** [opea-project/GenAIExamples#987]
### Priority

P1-Stopper

### OS type

Ubuntu

### Hardware type

Xeon-SPR

### Installation method

- [ ] Pull docker images from hub.docker.com
- [x] Build docker images from source

### Deploy method

- [X] Docker compose
- [ ] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

https://github.com/opea-project/GenAIExamples/commit/3c164f3aa25bae957e436a09628235e1a11d6e8d 

### Description

When I run the command to run the E2E service with tgi backend and re-rank: ```docker compose -f compose.yaml up -d``` after having set my environment variables (I am not on proxy network) and building each docker image, I get a port error for the tgi-service, even though there is no process occuring on this port. The error can be seen in the attached image. This bars me from launching the system entirely.

![Screenshot 2024-10-18 111259](https://github.com/user-attachments/assets/ace8ee69-9b9a-4f48-943c-b7f33cc3bc81)

### Reproduce steps

Followed these instructions exactly to run megaservice with re-ranker using tgi-backend starting from here: https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA/docker_compose/intel/cpu/xeon#-build-docker-images

**Comment by ZailiWang** [comment]
Hi, I cannot reproduce the issue. Would you try with command
```
ps -ef | grep 9009
```
to double check if the port is occupied?

**Comment by ZailiWang** [comment]
Closing the issue since no response for a while. Please re-open if the issue still hinders your development. thanks.
