### ISSUE TITLE
[Bug] ChatQnA browser interface gives an error - "failed to load chat content"

### ISSUE THREAD

**Issue by arun-gupta** [opea-project/GenAIExamples#989]
### Priority

Undecided

### OS type

Ubuntu

### Hardware type

Xeon-GNR

### Installation method

- [X] Pull docker images from hub.docker.com
- [ ] Build docker images from source

### Deploy method

- [X] Docker compose
- [ ] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

`latest`

### Description

Deployed ChatQnA example in IBM Cloud and got the UI interface. Typing any message in the chat window and clicking on Enter shows the following message:

<img width="559" alt="image" src="https://github.com/user-attachments/assets/213c56af-21b1-4513-b7fd-3f8d9695f80a">

Tried on a different browser and Incognito mode, no difference.

Clicking on `Paste Link` and `Confirm` keeps spinning.

### Reproduce steps

Follow the steps here to deploy anywhere https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA

**Comment by arun-gupta** [comment]
The following command works well:

```
curl http://${host_ip}:8888/v1/chatqna     -H "Content-Type: application/json"     -d '{
        "messages": "What is the revenue of Nike in 2023?"
    }'
```

**Comment by devpramod** [comment]
<img width="261" alt="image" src="https://github.com/user-attachments/assets/a6b2b411-fbc2-4b63-b08b-446953e8f1c4">

Facing a similar issue when I paste a link to use as context.

**Comment by mkbhanda** [comment]
@ashahba informed, is taking a look and will publish new opea-nginx image

**Comment by arun-gupta** [comment]
Just tried `latest` image on updated AWS instructions and got the same error
<img width="461" alt="image" src="https://github.com/user-attachments/assets/883f3117-78b7-4b19-9266-f0ba84d4e214">

**Comment by arun-gupta** [comment]
yes
