### ISSUE TITLE
[Bug] Docs: Instructions in README to migrate to conversational-UI missing some steps.

### ISSUE THREAD

**Issue by mkbhanda** [opea-project/GenAIExamples#991]
### Priority

P3-Medium

### OS type

Ubuntu

### Hardware type

Xeon-ICX

### Installation method

- [X] Pull docker images from hub.docker.com
- [ ] Build docker images from source

### Deploy method

- [X] Docker compose
- [ ] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

The host VM is not a concern here. Just the README https://github.com/opea-project/GenAIExamples/blob/main/ChatQnA/docker_compose/intel/cpu/xeon/README.md 

1) While the other services refer to BACKEND_SERVICE_ENDPOINT, etc this refers to APP_ variants
2) the proxy related environment variables missing
3) why is the dataprep dependency not mentioned, just chatQnA backend. Asking because the UI supports uploading documents, don't they need to be routed to the dataprep service for chunking etc.
Things are not working for me thus asking these questions.

chaqna-xeon-conversation-ui-server:
  image: opea/chatqna-conversation-ui:latest
  container_name: chatqna-xeon-conversation-ui-server
  environment:
    - APP_BACKEND_SERVICE_ENDPOINT=${BACKEND_SERVICE_ENDPOINT}
    - APP_DATA_PREP_SERVICE_URL=${DATAPREP_SERVICE_ENDPOINT}
  ports:
    - "5174:80"
  depends_on:
    - chaqna-xeon-backend-server
  ipc: host
  restart: always

### Description

Foloow ChatQnA readme to customize chatQnA compose file to use conversational ui

### Reproduce steps

edit compose.yaml and user docker to restart  (either with images in docker hub or built locally)

### Raw log

```shell
File upload results in spinning icon.
Pink javascript alert saying "failed to load chat content"
```

**Comment by louie-tsai** [comment]
@mkbhanda 
The conventional UI works for me.
![image](https://github.com/user-attachments/assets/bf17fb06-c5e2-45f3-a140-25d0a68a0b72)

Here are the modification for compose.yaml file following the README.
![image](https://github.com/user-attachments/assets/e81699ef-38b3-4751-a646-e3d638c68108)
here is my compose.yaml file.
[compose.txt](https://github.com/user-attachments/files/17467646/compose.txt)
Could you try again with same file or similar modification?

1. BACKEND_SERVICE_ENDPOINT should be set by https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA/ui/react. 
2. isn't proxy setting covered in the beginning? https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA/docker_compose/intel/cpu/xeon#quick-start-1setup-environment-variable
3. could you explain more for dataprep dependency?

**Comment by louie-tsai** [comment]
@mkbhanda 
if no further question, we will close the ticket for now.
